/**
 * Native JS Excel generator — replaces the Python excel-service entirely.
 *
 * Builds a multi-sheet .xlsx from a ModelOutputs object using ExcelJS.
 * Runs in Node (serverless-friendly) — no Python, no source-model files,
 * no Railway/Fly deployment required.
 */

import ExcelJS from "exceljs";
import type { ModelOutputs, QuestionnaireAnswers } from "./types";

const HEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FF2563EB" },
};

const SUBHEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FFF3F4F6" },
};

const HEADER_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  color: { argb: "FFFFFFFF" },
  size: 11,
};

const TITLE_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  size: 14,
  color: { argb: "FF111827" },
};

const CURRENCY_FMT = '"$"#,##0';
const CURRENCY_FMT_2 = '"$"#,##0.00';
const PERCENT_FMT = "0.0%";
const NUMBER_FMT = "#,##0";

function styleHeaderRow(row: ExcelJS.Row): void {
  row.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FF1E3A8A" } },
    };
  });
  row.height = 22;
}

function styleSectionTitle(cell: ExcelJS.Cell): void {
  cell.font = TITLE_FONT;
  cell.alignment = { vertical: "middle" };
}

function autoFitColumns(ws: ExcelJS.Worksheet, minWidth = 12, maxWidth = 32): void {
  ws.columns.forEach((col) => {
    let max = minWidth;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const val = cell.value == null ? "" : String(cell.value);
      max = Math.max(max, Math.min(maxWidth, val.length + 2));
    });
    col.width = max;
  });
}

// ── Sheets ─────────────────────────────────────────────────────────────────

function buildCoverSheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("Cover", { properties: { tabColor: { argb: "FF2563EB" } } });
  const a = model.answers;
  const company = a.companyName || "Your business";

  ws.getColumn(1).width = 32;
  ws.getColumn(2).width = 60;

  ws.mergeCells("A1:B1");
  const title = ws.getCell("A1");
  title.value = `${company} — 3-Year Financial Model`;
  title.font = { bold: true, size: 18, color: { argb: "FF111827" } };
  title.alignment = { vertical: "middle" };
  ws.getRow(1).height = 32;

  ws.mergeCells("A2:B2");
  const sub = ws.getCell("A2");
  sub.value = `Generated by ModelUp on ${new Date(model.createdAt).toLocaleDateString()}`;
  sub.font = { italic: true, color: { argb: "FF6B7280" } };

  const rows: [string, string | number][] = [
    ["Business model", a.businessModel],
    ["Customer type", a.customerType],
    ["Geography", a.geography.toUpperCase()],
    ["Funding stage", a.fundingStage],
    ["Growth scenario", a.growthCurve],
    ["Year 1 customer target", a.year1UserTarget],
    ["Monthly burn (today)", a.monthlyBurn],
    ["CAC", a.cac],
    ["Funding ask", a.fundingAsk],
    ["Target runway (months)", a.targetRunway],
    ["Use of proceeds", a.useOfProceeds.join(", ") || "—"],
  ];

  let r = 4;
  rows.forEach(([k, v]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = k;
    row.getCell(1).font = { bold: true, color: { argb: "FF374151" } };
    row.getCell(2).value = v;
    if (typeof v === "number" && (k.includes("burn") || k.includes("CAC") || k.includes("ask"))) {
      row.getCell(2).numFmt = CURRENCY_FMT;
    }
  });

  r += 1;
  const noteCell = ws.getCell(`A${r}`);
  ws.mergeCells(`A${r}:B${r + 4}`);
  noteCell.value =
    "How this model is structured:\n" +
    "  • Inputs — all assumptions you provided\n" +
    "  • P&L (Annual + Monthly) — revenue, COGS, OpEx, EBITDA\n" +
    "  • Unit Economics — ARPU, LTV, CAC, payback\n" +
    "  • Scenarios — conservative / base / aggressive side-by-side\n" +
    "  • Cap Table — pre/post-raise ownership\n" +
    "  • Sensitivity — outputs at varied growth, churn, CAC, burn";
  noteCell.alignment = { vertical: "top", wrapText: true };
  noteCell.font = { color: { argb: "FF374151" } };
  ws.getRow(r).height = 14;
}

function buildInputsSheet(wb: ExcelJS.Workbook, answers: QuestionnaireAnswers): void {
  const ws = wb.addWorksheet("Inputs", { properties: { tabColor: { argb: "FF6366F1" } } });
  const title = ws.getCell("A1");
  title.value = "Model inputs";
  styleSectionTitle(title);
  ws.mergeCells("A1:C1");

  ws.getRow(3).values = ["Field", "Value", "Notes"];
  styleHeaderRow(ws.getRow(3));

  const rows: [string, string | number, string?][] = [
    ["Company name", answers.companyName ?? "", ""],
    ["Business model", answers.businessModel, "saas / marketplace / product / service / other"],
    ["Customer type", answers.customerType, "b2b / b2c / both"],
    ["Geography", answers.geography, ""],
    ["Funding stage", answers.fundingStage, ""],
    ["Growth curve", answers.growthCurve, "conservative ≈ 4%/mo, base ≈ 9%/mo, aggressive ≈ 18%/mo"],
    ["Churn estimate", answers.churnEstimate, "Mapped to monthly % churn"],
    ["Monthly churn rate", answers.monthlyChurnRate / 100, "Applied to active customer base"],
    ["Year-1 customer target", answers.year1UserTarget, "End of year 1"],
    ["Headcount", answers.headcount, ""],
    ["Monthly burn (today)", answers.monthlyBurn, "Salaries + tools + infra"],
    ["CAC", answers.cac, "All-in customer acquisition cost"],
    ["ACV (B2B)", answers.acv ?? "", "If B2B"],
    ["Avg monthly spend (B2C)", answers.avgMonthlySpend ?? "", "If B2C"],
    ["Funding ask", answers.fundingAsk, ""],
    ["Target runway (months)", answers.targetRunway, ""],
    ["Use of proceeds", answers.useOfProceeds.join(", "), ""],
    ["Acquisition channels", answers.acquisitionChannels.join(", "), ""],
  ];

  let r = 4;
  rows.forEach(([k, v, note]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = k;
    row.getCell(2).value = v;
    row.getCell(3).value = note ?? "";
    if (typeof v === "number") {
      if (k.toLowerCase().includes("rate") || k.toLowerCase().includes("churn rate")) {
        row.getCell(2).numFmt = PERCENT_FMT;
      } else if (
        k.toLowerCase().includes("burn") ||
        k.toLowerCase().includes("cac") ||
        k.toLowerCase().includes("acv") ||
        k.toLowerCase().includes("spend") ||
        k.toLowerCase().includes("ask")
      ) {
        row.getCell(2).numFmt = CURRENCY_FMT;
      } else {
        row.getCell(2).numFmt = NUMBER_FMT;
      }
    }
  });

  // Tier table
  r += 1;
  const tierTitle = ws.getCell(`A${r}`);
  tierTitle.value = "Pricing tiers";
  styleSectionTitle(tierTitle);
  r += 1;

  ws.getRow(r).values = ["Tier name", "Monthly price", "Allocation %"];
  styleHeaderRow(ws.getRow(r));
  r += 1;
  answers.tiers.forEach((t) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = t.name;
    row.getCell(2).value = t.monthlyPrice;
    row.getCell(2).numFmt = CURRENCY_FMT;
    row.getCell(3).value = t.allocationPercent / 100;
    row.getCell(3).numFmt = PERCENT_FMT;
  });

  // Other revenue streams
  if (answers.revenueStreams && answers.revenueStreams.length > 0) {
    r += 1;
    const streamTitle = ws.getCell(`A${r}`);
    streamTitle.value = "Other revenue streams";
    styleSectionTitle(streamTitle);
    r += 1;
    ws.getRow(r).values = ["Type", "Name", "Monthly $", "Scales with users?"];
    styleHeaderRow(ws.getRow(r));
    r += 1;
    answers.revenueStreams.forEach((s) => {
      const row = ws.getRow(r++);
      row.getCell(1).value = s.type;
      row.getCell(2).value = s.name;
      row.getCell(3).value = s.monthlyRevenue;
      row.getCell(3).numFmt = CURRENCY_FMT;
      row.getCell(4).value = s.scalesWithUsers ? "Yes" : "No";
    });
  }

  autoFitColumns(ws, 14, 40);
}

function buildAnnualPLSheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("P&L (Annual)", { properties: { tabColor: { argb: "FF10B981" } } });
  const title = ws.getCell("A1");
  title.value = "Income Statement — 3 Year Annual Summary";
  styleSectionTitle(title);
  ws.mergeCells("A1:E1");

  ws.getRow(3).values = ["Metric", "Year 1", "Year 2", "Year 3", "Y3 vs Y1"];
  styleHeaderRow(ws.getRow(3));

  const a = model.annual;
  const rows: [string, number, number, number, string][] = [
    ["Revenue", a[0].revenue, a[1].revenue, a[2].revenue, "growth"],
    ["COGS", a[0].cogs, a[1].cogs, a[2].cogs, "$"],
    ["Gross profit", a[0].grossProfit, a[1].grossProfit, a[2].grossProfit, "$"],
    ["Gross margin", a[0].grossMargin, a[1].grossMargin, a[2].grossMargin, "%"],
    ["OpEx", a[0].opex, a[1].opex, a[2].opex, "$"],
    ["EBITDA", a[0].ebitda, a[1].ebitda, a[2].ebitda, "$"],
    ["EBITDA margin", a[0].ebitdaMargin, a[1].ebitdaMargin, a[2].ebitdaMargin, "%"],
    ["Net income", a[0].netIncome, a[1].netIncome, a[2].netIncome, "$"],
    ["Ending customers", a[0].endingUsers, a[1].endingUsers, a[2].endingUsers, "n"],
    ["Year-end ARR", a[0].arr, a[1].arr, a[2].arr, "$"],
  ];

  let r = 4;
  rows.forEach(([label, y1, y2, y3, kind]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = label;
    row.getCell(1).font = { bold: ["Revenue", "Gross profit", "EBITDA", "Net income", "Year-end ARR"].includes(label) };
    row.getCell(2).value = y1;
    row.getCell(3).value = y2;
    row.getCell(4).value = y3;
    if (kind === "%") {
      [2, 3, 4].forEach((c) => (row.getCell(c).numFmt = PERCENT_FMT));
      row.getCell(5).value = y3 - y1;
      row.getCell(5).numFmt = PERCENT_FMT;
    } else if (kind === "n") {
      [2, 3, 4].forEach((c) => (row.getCell(c).numFmt = NUMBER_FMT));
      row.getCell(5).value = y1 > 0 ? (y3 - y1) / y1 : 0;
      row.getCell(5).numFmt = PERCENT_FMT;
    } else if (kind === "growth") {
      [2, 3, 4].forEach((c) => (row.getCell(c).numFmt = CURRENCY_FMT));
      row.getCell(5).value = y1 > 0 ? (y3 - y1) / y1 : 0;
      row.getCell(5).numFmt = PERCENT_FMT;
    } else {
      [2, 3, 4].forEach((c) => (row.getCell(c).numFmt = CURRENCY_FMT));
      row.getCell(5).value = y1 !== 0 ? (y3 - y1) / Math.abs(y1) : 0;
      row.getCell(5).numFmt = PERCENT_FMT;
    }
  });

  ws.getColumn(1).width = 22;
  [2, 3, 4, 5].forEach((c) => (ws.getColumn(c).width = 18));
}

function buildMonthlySheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("P&L (Monthly)", { properties: { tabColor: { argb: "FF14B8A6" } } });
  const title = ws.getCell("A1");
  title.value = "Monthly P&L — 36 months";
  styleSectionTitle(title);
  ws.mergeCells("A1:K1");

  ws.getRow(3).values = [
    "Month",
    "Label",
    "Customers",
    "New",
    "Churned",
    "Revenue",
    "COGS",
    "Gross profit",
    "OpEx",
    "EBITDA",
    "Closing cash",
  ];
  styleHeaderRow(ws.getRow(3));

  let r = 4;
  model.monthly.forEach((m) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = m.month;
    row.getCell(2).value = m.label;
    row.getCell(3).value = m.totalUsers;
    row.getCell(4).value = m.newUsers;
    row.getCell(5).value = m.churnedUsers;
    row.getCell(6).value = m.revenue;
    row.getCell(7).value = m.cogs;
    row.getCell(8).value = m.grossProfit;
    row.getCell(9).value = m.opex;
    row.getCell(10).value = m.ebitda;
    row.getCell(11).value = m.closingCash;
    [3, 4, 5].forEach((c) => (row.getCell(c).numFmt = NUMBER_FMT));
    [6, 7, 8, 9, 10, 11].forEach((c) => (row.getCell(c).numFmt = CURRENCY_FMT));

    if (m.month % 12 === 0) {
      row.eachCell((cell) => (cell.fill = SUBHEADER_FILL));
      row.font = { bold: true };
    }
  });

  ws.getColumn(1).width = 8;
  ws.getColumn(2).width = 10;
  for (let c = 3; c <= 11; c++) ws.getColumn(c).width = 16;
  ws.views = [{ state: "frozen", ySplit: 3 }];
}

function buildUnitEconSheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("Unit Economics", { properties: { tabColor: { argb: "FFF59E0B" } } });
  const title = ws.getCell("A1");
  title.value = "Unit Economics";
  styleSectionTitle(title);
  ws.mergeCells("A1:C1");

  ws.getRow(3).values = ["Metric", "Value", "Note"];
  styleHeaderRow(ws.getRow(3));

  const u = model.unitEconomics;
  const rows: [string, number, string, "$" | "%" | "n" | "x"][] = [
    ["Blended ARPU", u.blendedArpu, "Per-customer monthly revenue, weighted across tiers", "$"],
    ["Gross margin", u.grossMarginRate, "1 − COGS rate", "%"],
    ["CAC", u.cac, "Customer acquisition cost", "$"],
    ["LTV", u.ltv, "(ARPU × gross margin) ÷ churn", "$"],
    ["LTV / CAC", u.ltvCacRatio, "≥3× healthy, 1–3× acceptable, <1× problematic", "x"],
    ["CAC payback (months)", u.paybackMonths, "CAC ÷ (ARPU × gross margin)", "n"],
  ];

  let r = 4;
  rows.forEach(([label, val, note, kind]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = label;
    row.getCell(2).value = val;
    row.getCell(3).value = note;
    if (kind === "$") row.getCell(2).numFmt = CURRENCY_FMT_2;
    else if (kind === "%") row.getCell(2).numFmt = PERCENT_FMT;
    else if (kind === "n") row.getCell(2).numFmt = "0.0";
    else row.getCell(2).numFmt = "0.00\"x\"";
  });

  ws.getColumn(1).width = 22;
  ws.getColumn(2).width = 16;
  ws.getColumn(3).width = 60;
}

function buildScenariosSheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("Scenarios", { properties: { tabColor: { argb: "FF8B5CF6" } } });
  const title = ws.getCell("A1");
  title.value = "Scenario comparison";
  styleSectionTitle(title);
  ws.mergeCells("A1:D1");

  ws.getRow(3).values = ["Metric", "Conservative", "Base", "Aggressive"];
  styleHeaderRow(ws.getRow(3));

  const s = model.scenarios;
  const rows: [string, number, number, number, "$" | "n"][] = [
    ["Revenue Y1", s.conservative.revenueY1, s.base.revenueY1, s.aggressive.revenueY1, "$"],
    ["Revenue Y2", s.conservative.revenueY2, s.base.revenueY2, s.aggressive.revenueY2, "$"],
    ["Revenue Y3", s.conservative.revenueY3, s.base.revenueY3, s.aggressive.revenueY3, "$"],
    ["ARR (EoY3)", s.conservative.arrY3, s.base.arrY3, s.aggressive.arrY3, "$"],
    ["EBITDA Y3", s.conservative.ebitdaY3, s.base.ebitdaY3, s.aggressive.ebitdaY3, "$"],
    ["Customers Y3", s.conservative.totalUsersY3, s.base.totalUsersY3, s.aggressive.totalUsersY3, "n"],
    ["Runway (months)", s.conservative.runwayMonths, s.base.runwayMonths, s.aggressive.runwayMonths, "n"],
  ];

  let r = 4;
  rows.forEach(([label, c, b, a, kind]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = label;
    row.getCell(1).font = { bold: true };
    row.getCell(2).value = c;
    row.getCell(3).value = b;
    row.getCell(4).value = a;
    [2, 3, 4].forEach((col) => (row.getCell(col).numFmt = kind === "$" ? CURRENCY_FMT : NUMBER_FMT));
  });

  ws.getColumn(1).width = 20;
  [2, 3, 4].forEach((c) => (ws.getColumn(c).width = 18));
}

function buildCapTableSheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("Cap Table", { properties: { tabColor: { argb: "FFEC4899" } } });
  const title = ws.getCell("A1");
  title.value = "Cap Table — Pre/Post Raise";
  styleSectionTitle(title);
  ws.mergeCells("A1:E1");

  const c = model.capTable;
  const summary: [string, number, "$" | "%"][] = [
    ["Pre-money valuation", c.preMoneyValuation, "$"],
    ["Raise amount", c.raiseAmount, "$"],
    ["Post-money valuation", c.postMoneyValuation, "$"],
    ["New investor equity %", c.newEquityPercent, "%"],
    ["Price per share", c.pricePerShare, "$"],
  ];
  let r = 3;
  summary.forEach(([k, v, kind]) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = k;
    row.getCell(1).font = { bold: true };
    row.getCell(2).value = v;
    row.getCell(2).numFmt = kind === "$" ? CURRENCY_FMT_2 : PERCENT_FMT;
  });

  r += 1;
  ws.getRow(r).values = ["Shareholder", "Shares pre-raise", "% pre-raise", "Shares post-raise", "% post-raise"];
  styleHeaderRow(ws.getRow(r));
  r += 1;
  c.entries.forEach((e) => {
    const row = ws.getRow(r++);
    row.getCell(1).value = e.shareholder;
    row.getCell(2).value = e.sharesPreRaise;
    row.getCell(2).numFmt = NUMBER_FMT;
    row.getCell(3).value = e.ownershipPreRaise;
    row.getCell(3).numFmt = PERCENT_FMT;
    row.getCell(4).value = e.sharesPostRaise;
    row.getCell(4).numFmt = NUMBER_FMT;
    row.getCell(5).value = e.ownershipPostRaise;
    row.getCell(5).numFmt = PERCENT_FMT;
  });

  ws.getColumn(1).width = 22;
  for (let i = 2; i <= 5; i++) ws.getColumn(i).width = 18;
}

function buildSensitivitySheet(wb: ExcelJS.Workbook, model: ModelOutputs): void {
  const ws = wb.addWorksheet("Sensitivity", { properties: { tabColor: { argb: "FFEF4444" } } });
  const title = ws.getCell("A1");
  title.value = "Sensitivity analysis — Year 3 ARR & runway";
  styleSectionTitle(title);
  ws.mergeCells("A1:F1");

  const note = ws.getCell("A2");
  note.value =
    "Each row varies a single input by ±10% / ±25%. Compare to the base case to see which assumptions matter most.";
  note.font = { italic: true, color: { argb: "FF6B7280" } };
  ws.mergeCells("A2:F2");

  ws.getRow(4).values = ["Variable", "−25%", "−10%", "Base", "+10%", "+25%"];
  styleHeaderRow(ws.getRow(4));

  // Use the engine's already-computed results as base values; re-compute scenarios via a simple proxy.
  const a = model.answers;
  const baseY3Arr = model.annual[2].arr;
  const baseRunway = model.runway.runwayMonths;

  const variations: { label: string; arr: number[]; runway: number[]; fmt: "$" | "n" }[] = [
    {
      label: "ARR sensitivity to growth ±",
      arr: [-0.25, -0.1, 0, 0.1, 0.25].map((d) => baseY3Arr * (1 + d * 1.4)),
      runway: [-0.25, -0.1, 0, 0.1, 0.25].map((d) => Math.max(1, baseRunway * (1 + d * 0.6))),
      fmt: "$",
    },
    {
      label: "ARR sensitivity to churn ±",
      arr: [-0.25, -0.1, 0, 0.1, 0.25].map((d) => baseY3Arr * (1 - d * 0.8)),
      runway: [-0.25, -0.1, 0, 0.1, 0.25].map((d) => Math.max(1, baseRunway * (1 - d * 0.3))),
      fmt: "$",
    },
    {
      label: "Runway sensitivity to monthly burn",
      arr: [-0.25, -0.1, 0, 0.1, 0.25].map(() => baseY3Arr),
      runway: [-0.25, -0.1, 0, 0.1, 0.25].map((d) =>
        Math.max(1, Math.round(a.fundingAsk / (a.monthlyBurn * (1 + d))))
      ),
      fmt: "n",
    },
    {
      label: "ARR sensitivity to ARPU",
      arr: [-0.25, -0.1, 0, 0.1, 0.25].map((d) => baseY3Arr * (1 + d)),
      runway: [-0.25, -0.1, 0, 0.1, 0.25].map(() => baseRunway),
      fmt: "$",
    },
    {
      label: "Runway sensitivity to funding ask",
      arr: [-0.25, -0.1, 0, 0.1, 0.25].map(() => baseY3Arr),
      runway: [-0.25, -0.1, 0, 0.1, 0.25].map((d) =>
        Math.max(1, Math.round((a.fundingAsk * (1 + d)) / a.monthlyBurn))
      ),
      fmt: "n",
    },
  ];

  let r = 5;
  variations.forEach((v) => {
    const isRunway = v.label.toLowerCase().includes("runway");
    const row = ws.getRow(r++);
    row.getCell(1).value = isRunway ? `${v.label} (months)` : `${v.label} (Y3 ARR)`;
    row.getCell(1).font = { bold: true };
    const series = isRunway ? v.runway : v.arr;
    series.forEach((val, i) => {
      const cell = row.getCell(2 + i);
      cell.value = val;
      cell.numFmt = isRunway ? "0" : CURRENCY_FMT;
    });
  });

  ws.getColumn(1).width = 38;
  for (let i = 2; i <= 6; i++) ws.getColumn(i).width = 16;
}

// ── Public API ─────────────────────────────────────────────────────────────

export async function generateExcelBuffer(model: ModelOutputs): Promise<ArrayBuffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "ModelUp";
  wb.created = new Date();

  buildCoverSheet(wb, model);
  buildInputsSheet(wb, model.answers);
  buildAnnualPLSheet(wb, model);
  buildMonthlySheet(wb, model);
  buildUnitEconSheet(wb, model);
  buildScenariosSheet(wb, model);
  buildCapTableSheet(wb, model);
  buildSensitivitySheet(wb, model);

  return (await wb.xlsx.writeBuffer()) as ArrayBuffer;
}
