#!/usr/bin/env python3
"""Append tour/coachmark keys to every locale dictionary (v2.10.0)."""

from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent / "src" / "i18n" / "dictionaries"

T = {
    "tour.next": {"es":"Siguiente","fr":"Suivant","de":"Weiter","pt":"Próximo","it":"Avanti","nl":"Volgende","tr":"Sonraki","uk":"Далі","ru":"Далее","ar":"التالي","hi":"अगला","bn":"পরবর্তী","zh":"下一步","ja":"次へ","id":"Berikutnya"},
    "tour.done": {"es":"Entendido","fr":"Compris","de":"Verstanden","pt":"Entendi","it":"Ho capito","nl":"Begrepen","tr":"Anladım","uk":"Зрозуміло","ru":"Понятно","ar":"فهمت","hi":"समझ गया","bn":"বুঝেছি","zh":"明白了","ja":"了解","id":"Mengerti"},
    "tour.skip": {"es":"Omitir","fr":"Ignorer","de":"Überspringen","pt":"Pular","it":"Salta","nl":"Overslaan","tr":"Atla","uk":"Пропустити","ru":"Пропустить","ar":"تخطي","hi":"छोड़ें","bn":"এড়িয়ে যান","zh":"跳过","ja":"スキップ","id":"Lewati"},
    "tour.step": {"es":"Paso {current} de {total}","fr":"Étape {current} sur {total}","de":"Schritt {current} von {total}","pt":"Passo {current} de {total}","it":"Passo {current} di {total}","nl":"Stap {current} van {total}","tr":"Adım {current} / {total}","uk":"Крок {current} з {total}","ru":"Шаг {current} из {total}","ar":"الخطوة {current} من {total}","hi":"चरण {current} / {total}","bn":"ধাপ {current} / {total}","zh":"第 {current} 步,共 {total} 步","ja":"ステップ {current} / {total}","id":"Langkah {current} dari {total}"},
    "tour.full_sensitivity_title": {"es":"Estresa cada input","fr":"Stress-testez chaque entrée","de":"Stresstest für jeden Input","pt":"Teste de estresse para cada input","it":"Stress-test su ogni input","nl":"Stress-test elke input","tr":"Her girdiyi stres testine tabi tut","uk":"Стрес-тест кожного входу","ru":"Стресс-тест каждого входа","ar":"اختبر كل مدخل تحت الضغط","hi":"प्रत्येक इनपुट का स्ट्रेस-टेस्ट करें","bn":"প্রতিটি ইনপুটের স্ট্রেস-টেস্ট","zh":"对每个输入做压力测试","ja":"すべての入力をストレステスト","id":"Stress-test setiap input"},
    "tour.full_sensitivity_body": {"es":"Arrastra cualquier control deslizante — churn, CAC, precio, burn — y todo el modelo se recalcula al instante. La forma más rápida de encontrar tus puntos de quiebre.","fr":"Faites glisser n'importe quel curseur — churn, CAC, prix, burn — et tout le modèle se recalcule en direct. Le moyen le plus rapide de trouver vos points de rupture.","de":"Ziehe einen beliebigen Slider — Churn, CAC, Preis, Burn — und das gesamte Modell rechnet live nach. Der schnellste Weg, deine Bruchstellen zu finden.","pt":"Arraste qualquer slider — churn, CAC, preço, burn — e todo o modelo recalcula ao vivo. A forma mais rápida de achar seus pontos de ruptura.","it":"Trascina qualsiasi cursore — churn, CAC, prezzo, burn — e tutto il modello si ricalcola in tempo reale. Il modo più veloce per trovare i tuoi break point.","nl":"Sleep een schuifregelaar — churn, CAC, prijs, burn — en het hele model herberekent live. De snelste manier om je breekpunten te vinden.","tr":"Herhangi bir kaydırıcıyı sürükle — churn, CAC, fiyat, burn — tüm model anında yeniden hesaplansın. Kırılma noktalarınızı bulmanın en hızlı yolu.","uk":"Перетягніть будь-який повзунок — churn, CAC, ціна, burn — і вся модель перерахується наживо. Найшвидший спосіб знайти точки злому.","ru":"Перетащите любой ползунок — churn, CAC, цена, burn — и вся модель пересчитается вживую. Самый быстрый способ найти точки слома.","ar":"اسحب أي شريط — churn، CAC، السعر، burn — وسيُعاد حساب النموذج بأكمله فورًا. أسرع طريقة لإيجاد نقاط الانكسار.","hi":"कोई भी स्लाइडर खींचें — churn, CAC, मूल्य, burn — और पूरा मॉडल लाइव पुनर्गणना करेगा। आपके ब्रेक पॉइंट खोजने का सबसे तेज़ तरीका।","bn":"যেকোনো স্লাইডার টানুন — churn, CAC, মূল্য, burn — পুরো মডেল লাইভ পুনঃগণনা করবে। আপনার ব্রেক পয়েন্ট খুঁজে পাওয়ার দ্রুততম উপায়।","zh":"拖动任意滑块 — churn、CAC、定价、burn — 整个模型实时重算。最快地找到你的临界点。","ja":"任意のスライダーをドラッグ — チャーン、CAC、価格、バーン — モデル全体がライブで再計算されます。ブレークポイントを見つける最速の方法。","id":"Geser slider mana saja — churn, CAC, harga, burn — seluruh model dihitung ulang langsung. Cara tercepat menemukan titik kritis Anda."},
    "tour.full_valuation_title": {"es":"Triangula tu valoración","fr":"Triangulez votre valorisation","de":"Triangulier deine Bewertung","pt":"Triangule sua valuation","it":"Triangola la tua valutazione","nl":"Trianguleer je waardering","tr":"Değerlemenizi üçgenleyin","uk":"Тріангулюйте оцінку","ru":"Триангулируйте оценку","ar":"ثلّث تقييمك","hi":"अपना मूल्यांकन त्रिकोणित करें","bn":"আপনার মূল্যায়ন ত্রিকোণীকরণ করুন","zh":"三角验证你的估值","ja":"バリュエーションをトライアンギュレート","id":"Triangulasi valuasi Anda"},
    "tour.full_valuation_body": {"es":"DCF y múltiplos por comparables lado a lado. Pro añade un constructor completo de WACC (CAPM + costo de deuda × escudo fiscal) y una matriz de sensibilidad.","fr":"DCF et multiples comparables côte à côte. Pro ajoute un constructeur WACC complet (CAPM + coût de la dette × bouclier fiscal) et une matrice de sensibilité.","de":"DCF und Comps-Multiples nebeneinander. Pro ergänzt einen vollständigen WACC-Builder (CAPM + Fremdkapitalkosten × Steuerschild) und eine Sensitivitätsmatrix.","pt":"DCF e múltiplos por comparáveis lado a lado. Pro adiciona um builder WACC completo (CAPM + custo da dívida × escudo fiscal) e uma matriz de sensibilidade.","it":"DCF e multipli comparabili affiancati. Pro aggiunge un builder WACC completo (CAPM + costo del debito × scudo fiscale) e una matrice di sensibilità.","nl":"DCF en comps-multiples naast elkaar. Pro voegt een volledige WACC-builder toe (CAPM + kosten van schuld × belastingschild) en een gevoeligheidsmatrix.","tr":"DCF ve karşılaştırılabilir çarpanlar yan yana. Pro tam WACC oluşturucu (CAPM + borç maliyeti × vergi kalkanı) ve duyarlılık matrisi ekler.","uk":"DCF та compsб-мультиплікатори поруч. Pro додає повний WACC-конструктор (CAPM + вартість боргу × податковий щит) і матрицю чутливості.","ru":"DCF и comps-мультипликаторы рядом. Pro добавляет полный конструктор WACC (CAPM + стоимость долга × налоговый щит) и матрицу чувствительности.","ar":"DCF ومضاعفات المقارنات جنبًا إلى جنب. يضيف Pro منشئ WACC كامل (CAPM + تكلفة الدين × درع ضريبي) ومصفوفة حساسية.","hi":"DCF और कॉम्प्स मल्टीपल साथ-साथ। Pro एक पूर्ण WACC बिल्डर (CAPM + ऋण लागत × टैक्स शील्ड) और संवेदनशीलता मैट्रिक्स जोड़ता है।","bn":"DCF এবং কম্পস মাল্টিপল পাশাপাশি। Pro একটি পূর্ণ WACC বিল্ডার (CAPM + ঋণ খরচ × ট্যাক্স শিল্ড) এবং সংবেদনশীলতা ম্যাট্রিক্স যোগ করে।","zh":"DCF 与可比公司倍数并排展示。Pro 增加完整的 WACC 构建器(CAPM + 债务成本 × 税盾)和敏感性矩阵。","ja":"DCF とコンプスマルチプルを並べて表示。Pro は完全な WACC ビルダー(CAPM + 負債コスト × 税効果)と感応度マトリクスを追加します。","id":"DCF dan multiple comps berdampingan. Pro menambahkan pembangun WACC penuh (CAPM + biaya hutang × tameng pajak) dan matriks sensitivitas."},
    "tour.full_captable_title": {"es":"Modela la dilución hasta Series B","fr":"Modélisez la dilution jusqu'en Series B","de":"Modelliere die Verwässerung bis Series B","pt":"Modele a diluição até a Series B","it":"Modella la diluizione fino al Series B","nl":"Modelleer verwatering tot Series B","tr":"Series B'ye kadar seyrelmeyi modelle","uk":"Змоделюйте розмиття до Series B","ru":"Смоделируйте размытие до Series B","ar":"اعرض التخفيف حتى Series B","hi":"Series B तक डाइल्यूशन मॉडल करें","bn":"Series B পর্যন্ত ডাইলিউশন মডেল করুন","zh":"建模至 Series B 的股权稀释","ja":"Series B までの希薄化をモデリング","id":"Modelkan dilusi hingga Series B"},
    "tour.full_captable_body": {"es":"Edita tus splits pre-seed y proyecta Series A/B con refrescos ESOP. La cascada muestra la propiedad del fundador en cada etapa.","fr":"Modifiez vos splits pré-seed et projetez les Series A/B avec refresh ESOP. La cascade montre la propriété du fondateur à chaque étape.","de":"Bearbeite deine Pre-Seed-Splits und projiziere Series A/B mit ESOP-Refreshes. Die Kaskade zeigt das Eigentum des Gründers in jeder Phase.","pt":"Edite seus splits pre-seed e projete Series A/B com refreshes ESOP. A cascata mostra a propriedade do fundador em cada etapa.","it":"Modifica i tuoi split pre-seed e proietta Series A/B con refresh ESOP. La cascata mostra la proprietà del fondatore in ogni fase.","nl":"Bewerk je pre-seed splits en projecteer Series A/B met ESOP-refreshes. De waterval toont oprichter-eigendom in elke fase.","tr":"Pre-seed bölünmelerinizi düzenleyin ve ESOP yenilemeleri ile Series A/B projeksiyonu yapın. Şelale, her aşamada kurucu sahipliğini gösterir.","uk":"Редагуйте pre-seed розподіли та проектуйте Series A/B з ESOP оновленнями. Каскад показує власність засновника на кожному етапі.","ru":"Редактируйте pre-seed разделения и проектируйте Series A/B с ESOP обновлениями. Каскад показывает владение основателя на каждом этапе.","ar":"عدّل تقسيمات Pre-seed وقم بإسقاط Series A/B مع تحديثات ESOP. الشلال يظهر ملكية المؤسس في كل مرحلة.","hi":"अपने प्री-सीड स्प्लिट संपादित करें और ESOP रिफ्रेश के साथ Series A/B प्रोजेक्ट करें। वाटरफ़ॉल हर चरण में फाउंडर ओनरशिप दिखाता है।","bn":"আপনার প্রি-সিড বিভাগ সম্পাদনা করুন এবং ESOP রিফ্রেশ সহ Series A/B প্রক্ষেপণ করুন। ওয়াটারফল প্রতিটি পর্যায়ে ফাউন্ডার মালিকানা দেখায়।","zh":"编辑你的种子前股权拆分,带 ESOP 刷新地预测 Series A/B。瀑布显示每个阶段的创始人股权。","ja":"プレシードのスプリットを編集し、ESOP リフレッシュ付きで Series A/B を予測。ウォーターフォールは各段階での創業者所有を表示します。","id":"Edit pemisahan pre-seed dan proyeksikan Series A/B dengan refresh ESOP. Waterfall menampilkan kepemilikan founder di setiap tahap."},
    "tour.full_calc_title": {"es":"Cada número, cada fórmula","fr":"Chaque nombre, chaque formule","de":"Jede Zahl, jede Formel","pt":"Cada número, cada fórmula","it":"Ogni numero, ogni formula","nl":"Elk getal, elke formule","tr":"Her sayı, her formül","uk":"Кожне число, кожна формула","ru":"Каждое число, каждая формула","ar":"كل رقم، كل صيغة","hi":"प्रत्येक संख्या, प्रत्येक सूत्र","bn":"প্রতিটি সংখ্যা, প্রতিটি সূত্র","zh":"每个数字,每个公式","ja":"すべての数値、すべての数式","id":"Setiap angka, setiap formula"},
    "tour.full_calc_body": {"es":"Seis secciones plegables muestran cómo se calculó cada métrica — útil cuando los inversores preguntan cómo llegaste al ARR del año 3.","fr":"Six sections pliables montrent comment chaque métrique a été calculée — utile quand les investisseurs demandent comment vous êtes arrivé à l'ARR de l'année 3.","de":"Sechs aufklappbare Abschnitte zeigen, wie jede Kennzahl berechnet wurde — nützlich, wenn Investoren fragen, wie du auf das Year-3-ARR kommst.","pt":"Seis seções expansíveis mostram como cada métrica foi calculada — útil quando investidores perguntam como você chegou ao ARR do ano 3.","it":"Sei sezioni espandibili mostrano come è stata calcolata ogni metrica — utile quando gli investitori chiedono come sei arrivato all'ARR dell'anno 3.","nl":"Zes uitklapbare secties tonen hoe elke metric is berekend — handig wanneer investeerders vragen hoe je tot de Y3 ARR komt.","tr":"Altı genişletilebilir bölüm, her metriğin nasıl hesaplandığını gösterir — yatırımcılar 3. yıl ARR'ye nasıl ulaştığınızı sorduğunda işe yarar.","uk":"Шість розгортуваних розділів показують, як обчислювалася кожна метрика — корисно, коли інвестори запитують, як ви дійшли до Y3 ARR.","ru":"Шесть раскрывающихся разделов показывают, как рассчитывалась каждая метрика — полезно, когда инвесторы спрашивают, как вы пришли к Y3 ARR.","ar":"ستة أقسام قابلة للتوسيع تُظهر كيف تم حساب كل مقياس — مفيد عندما يسأل المستثمرون كيف وصلت إلى ARR السنة 3.","hi":"छह विस्तार-योग्य खंड दिखाते हैं कि प्रत्येक मीट्रिक की गणना कैसे हुई — उपयोगी जब निवेशक पूछते हैं कि आप Y3 ARR तक कैसे पहुँचे।","bn":"ছয়টি সম্প্রসারণযোগ্য বিভাগ দেখায় প্রতিটি মেট্রিক কীভাবে গণনা হয়েছিল — যখন বিনিয়োগকারীরা জিজ্ঞাসা করেন আপনি Y3 ARR-এ কীভাবে পৌঁছেছেন তখন কাজে আসে।","zh":"六个可折叠部分展示每个指标是如何计算的 — 当投资人询问你如何得出第 3 年 ARR 时非常有用。","ja":"6 つの展開可能なセクションで各メトリクスの計算方法を表示。投資家が Year-3 ARR にどう到達したか尋ねたときに役立ちます。","id":"Enam bagian yang dapat diperluas menampilkan cara perhitungan setiap metrik — berguna saat investor bertanya bagaimana Anda sampai pada ARR Tahun 3."},
}

LOCALES = ["es","fr","de","pt","it","nl","tr","uk","ru","ar","hi","bn","zh","ja","id"]

def append_to_locale(code):
    path = ROOT / f"{code}.ts"
    content = path.read_text(encoding="utf-8")
    if '"tour.next"' in content:
        print(f"  {code}: already has tour.next, skipping")
        return
    lines = ['', '  // ── Tour / coachmarks ───────────────────────────────────────────────────']
    for key, per_lang in T.items():
        value = per_lang.get(code, key)
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'  "{key}": "{escaped}",')
    block = "\n".join(lines) + "\n"
    if not content.rstrip().endswith("};"):
        print(f"  {code}: unexpected ending, skipping")
        return
    new = content.rstrip().rstrip("};").rstrip() + "\n" + block + "};\n"
    path.write_text(new, encoding="utf-8")
    print(f"  {code}: appended {len(T)} keys")

for code in LOCALES:
    append_to_locale(code)
print("done.")
