#!/usr/bin/env python3
"""
Append the v2.7.0 i18n batch (output pages + pricing) into every locale
dictionary. Source-of-truth is en.ts; this script writes the translations
for the other 15 locales.

For each new key, we provide the translation per language. Where a language
isn't covered (rare for short labels), we fall back to English so the type
checker stays happy and the UI never breaks.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "src" / "i18n" / "dictionaries"

# Per-language translations. Missing keys fall back to English.
# Keep this dict ordered the same as en.ts for easy diffing.
TRANSLATIONS = {
    # ===== TABS =====
    "tab.overview":      {"es":"Resumen","fr":"Vue d'ensemble","de":"Übersicht","pt":"Visão geral","it":"Panoramica","nl":"Overzicht","tr":"Genel bakış","uk":"Огляд","ru":"Обзор","ar":"نظرة عامة","hi":"अवलोकन","bn":"সারসংক্ষেপ","zh":"概览","ja":"概要","id":"Ringkasan"},
    "tab.pl":            {"es":"P&G","fr":"P&L","de":"GuV","pt":"DRE","it":"P&L","nl":"W&V","tr":"P&L","uk":"P&L","ru":"P&L","ar":"الأرباح والخسائر","hi":"P&L","bn":"P&L","zh":"损益","ja":"P&L","id":"P&L"},
    "tab.cash_flow":     {"es":"Flujo de caja","fr":"Trésorerie","de":"Cashflow","pt":"Fluxo de caixa","it":"Flusso di cassa","nl":"Kasstroom","tr":"Nakit akışı","uk":"Грошовий потік","ru":"Денежный поток","ar":"التدفق النقدي","hi":"कैश फ़्लो","bn":"ক্যাশ ফ্লো","zh":"现金流","ja":"キャッシュフロー","id":"Arus kas"},
    "tab.sources_uses":  {"es":"Fuentes y usos","fr":"Sources & emplois","de":"Mittel & Verwendung","pt":"Fontes & usos","it":"Fonti & impieghi","nl":"Sources & uses","tr":"Kaynaklar & kullanım","uk":"Джерела і використання","ru":"Источники и использование","ar":"المصادر والاستخدامات","hi":"स्रोत और उपयोग","bn":"উৎস ও ব্যবহার","zh":"来源与用途","ja":"資金調達と使途","id":"Sumber & penggunaan"},
    "tab.unit_econ":     {"es":"Unit economics","fr":"Unit economics","de":"Unit Economics","pt":"Unit economics","it":"Unit economics","nl":"Unit economics","tr":"Birim ekonomisi","uk":"Юніт-економіка","ru":"Юнит-экономика","ar":"اقتصاديات الوحدة","hi":"यूनिट इकोनॉमिक्स","bn":"ইউনিট ইকোনমিক্স","zh":"单位经济","ja":"ユニットエコノミクス","id":"Unit economics"},
    "tab.scenarios":     {"es":"Escenarios","fr":"Scénarios","de":"Szenarien","pt":"Cenários","it":"Scenari","nl":"Scenario's","tr":"Senaryolar","uk":"Сценарії","ru":"Сценарии","ar":"السيناريوهات","hi":"परिदृश्य","bn":"পরিদৃশ্য","zh":"情景","ja":"シナリオ","id":"Skenario"},
    "tab.cap_table":     {"es":"Cap table","fr":"Cap table","de":"Cap Table","pt":"Cap table","it":"Cap table","nl":"Cap table","tr":"Sermaye yapısı","uk":"Cap table","ru":"Cap table","ar":"جدول رأس المال","hi":"कैप टेबल","bn":"ক্যাপ টেবিল","zh":"股权结构","ja":"キャップテーブル","id":"Cap table"},
    "tab.valuation":     {"es":"Valoración","fr":"Valorisation","de":"Bewertung","pt":"Valuation","it":"Valutazione","nl":"Waardering","tr":"Değerleme","uk":"Оцінка","ru":"Оценка","ar":"التقييم","hi":"मूल्यांकन","bn":"মূল্যায়ন","zh":"估值","ja":"バリュエーション","id":"Valuasi"},
    "tab.sensitivity":   {"es":"Sensibilidad","fr":"Sensibilité","de":"Sensitivität","pt":"Sensibilidade","it":"Sensibilità","nl":"Gevoeligheid","tr":"Duyarlılık","uk":"Чутливість","ru":"Чувствительность","ar":"الحساسية","hi":"संवेदनशीलता","bn":"সংবেদনশীলতা","zh":"敏感性","ja":"感応度","id":"Sensitivitas"},
    "tab.calculations":  {"es":"Cálculos","fr":"Calculs","de":"Berechnungen","pt":"Cálculos","it":"Calcoli","nl":"Berekeningen","tr":"Hesaplamalar","uk":"Розрахунки","ru":"Расчёты","ar":"الحسابات","hi":"गणनाएँ","bn":"গণনা","zh":"计算","ja":"計算","id":"Perhitungan"},

    # ===== PG (page-level common) =====
    "pg.year_n_arr": {"es":"ARR año {n}","fr":"ARR année {n}","de":"ARR Jahr {n}","pt":"ARR ano {n}","it":"ARR anno {n}","nl":"ARR jaar {n}","tr":"{n}. yıl ARR","uk":"ARR Рік {n}","ru":"ARR Год {n}","ar":"ARR السنة {n}","hi":"वर्ष {n} ARR","bn":"বছর {n} ARR","zh":"第 {n} 年 ARR","ja":"{n} 年目 ARR","id":"ARR tahun {n}"},
    "pg.year_n_customers": {"es":"Clientes año {n}","fr":"Clients année {n}","de":"Kunden Jahr {n}","pt":"Clientes ano {n}","it":"Clienti anno {n}","nl":"Klanten jaar {n}","tr":"{n}. yıl müşteri","uk":"Клієнти Рік {n}","ru":"Клиенты Год {n}","ar":"عملاء السنة {n}","hi":"वर्ष {n} ग्राहक","bn":"বছর {n} গ্রাহক","zh":"第 {n} 年客户","ja":"{n} 年目顧客","id":"Pelanggan tahun {n}"},
    "pg.annual_recurring_revenue": {"es":"Ingresos recurrentes anuales","fr":"Revenu récurrent annuel","de":"Jährlich wiederkehrender Umsatz","pt":"Receita recorrente anual","it":"Ricavi ricorrenti annuali","nl":"Jaarlijks terugkerende omzet","tr":"Yıllık tekrarlayan gelir","uk":"Річний регулярний дохід","ru":"Годовой повторяющийся доход","ar":"الإيرادات السنوية المتكررة","hi":"वार्षिक आवर्ती राजस्व","bn":"বার্ষিক পুনরাবৃত্ত আয়","zh":"年度经常性收入","ja":"年間経常収益","id":"Pendapatan tahunan berulang"},
    "pg.cash_runway":    {"es":"Runway de efectivo","fr":"Trésorerie restante","de":"Cash Runway","pt":"Runway de caixa","it":"Runway di cassa","nl":"Cash runway","tr":"Nakit runway","uk":"Грошовий runway","ru":"Денежный runway","ar":"Runway النقد","hi":"कैश रनवे","bn":"ক্যাশ রানওয়ে","zh":"现金 runway","ja":"キャッシュランウェイ","id":"Runway kas"},
    "pg.runway":         {"es":"Runway","fr":"Runway","de":"Runway","pt":"Runway","it":"Runway","nl":"Runway","tr":"Runway","uk":"Runway","ru":"Runway","ar":"Runway","hi":"रनवे","bn":"রানওয়ে","zh":"Runway","ja":"ランウェイ","id":"Runway"},
    "pg.raise_label":    {"es":"Ronda: {amount}","fr":"Levée : {amount}","de":"Runde: {amount}","pt":"Rodada: {amount}","it":"Round: {amount}","nl":"Raise: {amount}","tr":"Yatırım: {amount}","uk":"Раунд: {amount}","ru":"Раунд: {amount}","ar":"الجولة: {amount}","hi":"राउंड: {amount}","bn":"রাউন্ড: {amount}","zh":"融资:{amount}","ja":"ラウンド:{amount}","id":"Ronde: {amount}"},
    "pg.break_even":     {"es":"Break-even (EBITDA+)","fr":"Seuil de rentabilité (EBITDA+)","de":"Break-even (EBITDA+)","pt":"Break-even (EBITDA+)","it":"Break-even (EBITDA+)","nl":"Break-even (EBITDA+)","tr":"Başabaş (EBITDA+)","uk":"Точка беззбитковості (EBITDA+)","ru":"Точка безубыточности (EBITDA+)","ar":"التعادل (EBITDA+)","hi":"ब्रेक-ईवन (EBITDA+)","bn":"ব্রেক-ইভেন (EBITDA+)","zh":"盈亏平衡 (EBITDA+)","ja":"損益分岐点 (EBITDA+)","id":"Titik impas (EBITDA+)"},
    "pg.break_even_sub": {"es":"Mes {month}","fr":"Mois {month}","de":"Monat {month}","pt":"Mês {month}","it":"Mese {month}","nl":"Maand {month}","tr":"Ay {month}","uk":"Місяць {month}","ru":"Месяц {month}","ar":"الشهر {month}","hi":"महीना {month}","bn":"মাস {month}","zh":"第 {month} 月","ja":"{month} か月目","id":"Bulan {month}"},
    "pg.break_even_not_reached": {"es":"No alcanzado en el pronóstico","fr":"Non atteint dans la prévision","de":"In Prognose nicht erreicht","pt":"Não alcançado na projeção","it":"Non raggiunto nelle previsioni","nl":"Niet bereikt in prognose","tr":"Tahminde ulaşılamadı","uk":"Не досягнуто в прогнозі","ru":"Не достигнуто в прогнозе","ar":"لم يتحقق في التوقع","hi":"पूर्वानुमान में नहीं पहुँचा","bn":"পূর্বাভাসে পৌঁছায়নি","zh":"预测期内未达到","ja":"予測内で到達せず","id":"Tidak tercapai dalam prakiraan"},
    "pg.first_profit_year": {"es":"Primer año rentable","fr":"Première année rentable","de":"Erstes profitables Jahr","pt":"Primeiro ano lucrativo","it":"Primo anno in profitto","nl":"Eerste winstgevende jaar","tr":"İlk kârlı yıl","uk":"Перший прибутковий рік","ru":"Первый прибыльный год","ar":"أول سنة مربحة","hi":"पहला लाभदायक वर्ष","bn":"প্রথম লাভজনক বছর","zh":"首个盈利年","ja":"初の黒字年","id":"Tahun pertama untung"},
    "pg.first_profit_sub": {"es":"Ingreso neto anual > 0","fr":"Résultat net annuel > 0","de":"Jährliches Nettoeinkommen > 0","pt":"Lucro líquido anual > 0","it":"Utile netto annuale > 0","nl":"Jaarlijks netto-inkomen > 0","tr":"Yıllık net gelir > 0","uk":"Річний чистий дохід > 0","ru":"Годовой чистый доход > 0","ar":"صافي الدخل السنوي > 0","hi":"वार्षिक शुद्ध आय > 0","bn":"বার্ষিক নিট আয় > 0","zh":"年度净利润 > 0","ja":"年間純利益 > 0","id":"Laba bersih tahunan > 0"},
    "pg.ltv_cac":        {"es":"LTV / CAC","fr":"LTV / CAC","de":"LTV / CAC","pt":"LTV / CAC","it":"LTV / CAC","nl":"LTV / CAC","tr":"LTV / CAC","uk":"LTV / CAC","ru":"LTV / CAC","ar":"LTV / CAC","hi":"LTV / CAC","bn":"LTV / CAC","zh":"LTV / CAC","ja":"LTV / CAC","id":"LTV / CAC"},
    "pg.ltv_cac_healthy":{"es":"Ratio saludable","fr":"Ratio sain","de":"Gesundes Verhältnis","pt":"Razão saudável","it":"Rapporto sano","nl":"Gezonde ratio","tr":"Sağlıklı oran","uk":"Здорове співвідношення","ru":"Здоровое соотношение","ar":"نسبة صحية","hi":"स्वस्थ अनुपात","bn":"স্বাস্থ্যকর অনুপাত","zh":"健康比率","ja":"健全な比率","id":"Rasio sehat"},
    "pg.ltv_cac_monitor":{"es":"Vigilar de cerca","fr":"À surveiller","de":"Genau beobachten","pt":"Monitorar de perto","it":"Da monitorare","nl":"Nauwlettend volgen","tr":"Yakından izle","uk":"Уважно стежити","ru":"Внимательно следить","ar":"راقب عن كثب","hi":"बारीकी से निगरानी","bn":"নিবিড়ভাবে পর্যবেক্ষণ","zh":"密切关注","ja":"要注意","id":"Pantau ketat"},
    "pg.dcf_ev":         {"es":"Valor empresa DCF","fr":"Valeur d'entreprise DCF","de":"DCF Unternehmenswert","pt":"Valor de empresa DCF","it":"Enterprise value DCF","nl":"DCF ondernemingswaarde","tr":"DCF şirket değeri","uk":"Вартість підприємства DCF","ru":"Стоимость предприятия DCF","ar":"قيمة المنشأة DCF","hi":"DCF एंटरप्राइज मूल्य","bn":"DCF এন্টারপ্রাইজ মূল্য","zh":"DCF 企业价值","ja":"DCF 企業価値","id":"Nilai perusahaan DCF"},
    "pg.dcf_at_rate":    {"es":"al {rate}% de descuento","fr":"@ {rate}% d'actualisation","de":"@ {rate}% Diskontsatz","pt":"a {rate}% de desconto","it":"@ {rate}% sconto","nl":"@ {rate}% disconto","tr":"%{rate} iskonto","uk":"при {rate}% знижці","ru":"при {rate}% дисконте","ar":"بخصم {rate}%","hi":"{rate}% डिस्काउंट","bn":"{rate}% ডিসকাউন্ট","zh":"@ {rate}% 折现","ja":"@ {rate}% 割引","id":"@ diskon {rate}%"},
    "pg.ebitda_mult_value": {"es":"Valor por múltiplo EBITDA","fr":"Valeur par multiple EBITDA","de":"EBITDA-Multiple-Wert","pt":"Valor por múltiplo EBITDA","it":"Valore multiplo EBITDA","nl":"EBITDA-multiple waarde","tr":"EBITDA çarpan değeri","uk":"Вартість за мультиплікатором EBITDA","ru":"Стоимость по мультипликатору EBITDA","ar":"قيمة مضاعف EBITDA","hi":"EBITDA मल्टीपल मूल्य","bn":"EBITDA মাল্টিপল মূল্য","zh":"EBITDA 倍数价值","ja":"EBITDA マルチプル価値","id":"Nilai multiple EBITDA"},
    "pg.year_arr_label": {"es":"ARR {label}","fr":"ARR {label}","de":"ARR {label}","pt":"ARR {label}","it":"ARR {label}","nl":"ARR {label}","tr":"{label} ARR","uk":"ARR {label}","ru":"ARR {label}","ar":"{label} ARR","hi":"{label} ARR","bn":"{label} ARR","zh":"{label} ARR","ja":"{label} ARR","id":"ARR {label}"},
    "pg.year_ebitda_label": {"es":"EBITDA {label}","fr":"EBITDA {label}","de":"EBITDA {label}","pt":"EBITDA {label}","it":"EBITDA {label}","nl":"EBITDA {label}","tr":"{label} EBITDA","uk":"EBITDA {label}","ru":"EBITDA {label}","ar":"{label} EBITDA","hi":"{label} EBITDA","bn":"{label} EBITDA","zh":"{label} EBITDA","ja":"{label} EBITDA","id":"EBITDA {label}"},
    "pg.year_paying_customers": {"es":"Clientes de pago (fin de año)","fr":"Clients payants (fin d'année)","de":"Zahlende Kunden (Jahresende)","pt":"Clientes pagantes (fim do ano)","it":"Clienti paganti (fine anno)","nl":"Betalende klanten (EoY)","tr":"Ödeme yapan müşteriler (yıl sonu)","uk":"Платні клієнти (на кінець року)","ru":"Платные клиенты (на конец года)","ar":"العملاء الدافعون (نهاية السنة)","hi":"भुगतान करने वाले ग्राहक (वर्ष-अंत)","bn":"পেইড গ্রাহক (বছরের শেষে)","zh":"付费客户(年末)","ja":"有料顧客(年末)","id":"Pelanggan berbayar (akhir tahun)"},
    "pg.years_model_title": {"es":"{company} — Modelo financiero a {years} años","fr":"{company} — Modèle financier sur {years} ans","de":"{company} — {years}-Jahres-Finanzmodell","pt":"{company} — Modelo financeiro de {years} anos","it":"{company} — Modello finanziario a {years} anni","nl":"{company} — {years}-jaars financieel model","tr":"{company} — {years} yıllık finansal model","uk":"{company} — {years}-річна фінансова модель","ru":"{company} — {years}-летняя финансовая модель","ar":"{company} — نموذج مالي لـ {years} سنوات","hi":"{company} — {years}-वर्षीय वित्तीय मॉडल","bn":"{company} — {years}-বছরের আর্থিক মডেল","zh":"{company} — {years} 年财务模型","ja":"{company} — {years} 年間財務モデル","id":"{company} — Model keuangan {years} tahun"},
    "pg.generated_on":   {"es":"Origen: {source} · Generado el {date}","fr":"Source : {source} · Généré le {date}","de":"Quelle: {source} · Generiert am {date}","pt":"Origem: {source} · Gerado em {date}","it":"Origine: {source} · Generato il {date}","nl":"Bron: {source} · Gegenereerd op {date}","tr":"Kaynak: {source} · {date} tarihinde oluşturuldu","uk":"Джерело: {source} · Створено {date}","ru":"Источник: {source} · Создано {date}","ar":"المصدر: {source} · أُنشئ في {date}","hi":"स्रोत: {source} · {date} को बनाया गया","bn":"উৎস: {source} · {date} এ তৈরি","zh":"来源:{source} · 生成于 {date}","ja":"ソース: {source} · 生成日 {date}","id":"Sumber: {source} · Dibuat {date}"},
    "pg.excel_note":     {"es":"Abre el archivo Excel en Excel o Google Sheets para calcular las fórmulas.","fr":"Ouvrez le fichier Excel dans Excel ou Google Sheets pour calculer les formules.","de":"Öffne die Excel-Datei in Excel oder Google Sheets, um Formeln zu berechnen.","pt":"Abra o arquivo Excel no Excel ou Google Sheets para calcular as fórmulas.","it":"Apri il file Excel in Excel o Google Sheets per calcolare le formule.","nl":"Open het Excel-bestand in Excel of Google Sheets om formules te berekenen.","tr":"Formülleri otomatik hesaplamak için Excel dosyasını Excel veya Google Sheets'te aç.","uk":"Відкрийте файл Excel у Excel або Google Sheets, щоб обчислити формули.","ru":"Откройте файл Excel в Excel или Google Sheets для вычисления формул.","ar":"افتح ملف Excel في Excel أو Google Sheets لحساب الصيغ تلقائيًا.","hi":"फ़ॉर्मूले की गणना के लिए Excel फ़ाइल को Excel या Google Sheets में खोलें।","bn":"ফর্মুলা গণনা করতে Excel ফাইলটি Excel বা Google Sheets-এ খুলুন।","zh":"在 Excel 或 Google Sheets 中打开此 Excel 文件以自动计算公式。","ja":"数式を自動計算するには、Excel または Google Sheets で Excel ファイルを開いてください。","id":"Buka file Excel di Excel atau Google Sheets untuk menghitung rumus otomatis."},
    "pg.exporting":      {"es":"Exportando…","fr":"Export en cours…","de":"Wird exportiert…","pt":"Exportando…","it":"Esportazione…","nl":"Exporteren…","tr":"Dışa aktarılıyor…","uk":"Експорт…","ru":"Экспорт…","ar":"جارٍ التصدير…","hi":"निर्यात…","bn":"রপ্তানি হচ্ছে…","zh":"导出中…","ja":"エクスポート中…","id":"Mengekspor…"},
    "pg.download_xlsx":  {"es":"Descargar .xlsx","fr":"Télécharger .xlsx","de":".xlsx herunterladen","pt":"Baixar .xlsx","it":"Scarica .xlsx","nl":".xlsx downloaden",   "tr":".xlsx indir","uk":"Завантажити .xlsx","ru":"Скачать .xlsx","ar":"تنزيل .xlsx","hi":".xlsx डाउनलोड","bn":".xlsx ডাউনলোড","zh":"下载 .xlsx","ja":".xlsx をダウンロード","id":"Unduh .xlsx"},
    "pg.excel_ready":    {"es":"Modelo Excel listo para descargar.","fr":"Modèle Excel prêt à télécharger.","de":"Excel-Modell zum Download bereit.","pt":"Modelo Excel pronto para download.","it":"Modello Excel pronto al download.","nl":"Excel-model klaar om te downloaden.","tr":"Excel modeli indirmeye hazır.","uk":"Excel-модель готова до завантаження.","ru":"Excel-модель готова к скачиванию.","ar":"نموذج Excel جاهز للتنزيل.","hi":"Excel मॉडल डाउनलोड के लिए तैयार।","bn":"Excel মডেল ডাউনলোডের জন্য প্রস্তুত।","zh":"Excel 模型可下载。","ja":"Excel モデルをダウンロードできます。","id":"Model Excel siap diunduh."},
    "pg.excel_ready_body": {"es":"El archivo {source} poblado incluye todas tus entradas inyectadas en la hoja Scen. Ábrelo en Excel o Google Sheets para autocalcular cada fórmula.","fr":"Le fichier {source} pré-rempli inclut toutes vos données injectées dans la feuille Scen. Ouvrez-le dans Excel ou Google Sheets pour auto-calculer chaque formule.","de":"Die gefüllte {source}-Datei enthält alle deine Eingaben im Scen-Sheet. Öffne sie in Excel oder Google Sheets, um jede Formel automatisch zu berechnen.","pt":"O arquivo {source} preenchido inclui todas as suas entradas injetadas na aba Scen. Abra no Excel ou Google Sheets para calcular cada fórmula automaticamente.","it":"Il file {source} popolato include tutti i tuoi input nel foglio Scen. Aprilo in Excel o Google Sheets per calcolare automaticamente ogni formula.","nl":"Het gevulde {source}-bestand bevat al je inputs in het Scen-blad. Open in Excel of Google Sheets om elke formule automatisch te berekenen.","tr":"Doldurulmuş {source} dosyası tüm girdilerinizi Scen sayfasına enjekte edilmiş şekilde içerir. Excel veya Google Sheets'te açın.","uk":"Заповнений файл {source} містить усі ваші введення в аркуші Scen. Відкрийте в Excel або Google Sheets для автоматичного обчислення формул.","ru":"Заполненный файл {source} содержит все ваши вводы в листе Scen. Откройте в Excel или Google Sheets для автоматического расчёта формул.","ar":"يتضمّن ملف {source} المُعبّأ كل مدخلاتك مدمجةً في ورقة Scen. افتحه في Excel أو Google Sheets لحساب كل صيغة تلقائيًا.","hi":"भरी हुई {source} फ़ाइल में Scen शीट में आपके सभी इनपुट शामिल हैं। ऑटो-कैलकुलेट के लिए Excel या Google Sheets में खोलें।","bn":"পূরণ করা {source} ফাইলে Scen শীটে আপনার সব ইনপুট রয়েছে। প্রতিটি ফর্মুলা স্বয়ংক্রিয়ভাবে গণনা করতে Excel বা Google Sheets-এ খুলুন।","zh":"已填充的 {source} 文件包含所有输入并已注入 Scen 工作表。在 Excel 或 Google Sheets 中打开以自动计算公式。","ja":"入力済み {source} ファイルには Scen シートにすべての入力が含まれます。Excel または Google Sheets で開いて数式を自動計算してください。","id":"File {source} yang terisi mencakup semua input Anda di lembar Scen. Buka di Excel atau Google Sheets untuk menghitung otomatis."},

    # ===== PREVIEW =====
    "preview.free_preview_badge": {"es":"Vista previa gratuita","fr":"Aperçu gratuit","de":"Kostenlose Vorschau","pt":"Pré-visualização gratuita","it":"Anteprima gratuita","nl":"Gratis preview","tr":"Ücretsiz önizleme","uk":"Безкоштовний попередній перегляд","ru":"Бесплатный предпросмотр","ar":"معاينة مجانية","hi":"मुफ़्त प्रीव्यू","bn":"ফ্রি প্রিভিউ","zh":"免费预览","ja":"無料プレビュー","id":"Pratinjau gratis"},
    "preview.cash_runway_text": {"es":"Con un burn mensual de {burn}, tu ronda de {raise} te da {runway} de runway.","fr":"Avec un burn mensuel de {burn}, votre levée de {raise} vous donne {runway} de trésorerie.","de":"Bei einem monatlichen Burn von {burn} gibt dir die {raise}-Runde {runway} Runway.","pt":"Com burn mensal de {burn}, sua rodada de {raise} te dá {runway} de runway.","it":"Con un burn mensile di {burn}, il tuo round da {raise} ti dà {runway} di runway.","nl":"Met een maandelijkse burn van {burn} geeft je raise van {raise} je {runway} runway.","tr":"Aylık {burn} burn ile {raise} yatırımınız size {runway} runway sağlar.","uk":"При місячному burn {burn}, ваш раунд {raise} дає {runway} runway.","ru":"При месячном burn {burn}, ваш раунд {raise} даёт {runway} runway.","ar":"بمعدل إنفاق شهري {burn}، تمنحك جولة {raise} مدة runway قدرها {runway}.","hi":"मासिक बर्न {burn} पर, आपकी {raise} राउंड {runway} रनवे देती है।","bn":"মাসিক burn {burn}-এ, আপনার {raise} রাউন্ড {runway} runway দেয়।","zh":"以 {burn} 月度烧钱率,你的 {raise} 融资给你 {runway} 的 runway。","ja":"月間バーン {burn} で、{raise} ラウンドは {runway} のランウェイを提供します。","id":"Dengan burn bulanan {burn}, ronde {raise} Anda memberi {runway} runway."},
    "preview.pl_summary_title": {"es":"Resumen de P&G a 5 años","fr":"Résumé P&L sur 5 ans","de":"5-Jahres-GuV-Übersicht","pt":"Resumo DRE de 5 anos","it":"Riepilogo P&L a 5 anni","nl":"5-jaars W&V-samenvatting","tr":"5 yıllık P&L özeti","uk":"Підсумок P&L за 5 років","ru":"Сводка P&L за 5 лет","ar":"ملخص الأرباح والخسائر لـ 5 سنوات","hi":"5-वर्षीय P&L सारांश","bn":"৫-বছরের P&L সারসংক্ষেপ","zh":"5 年损益摘要","ja":"5 年間 P&L サマリー","id":"Ringkasan P&L 5 tahun"},
    "preview.pl_summary_sub": {"es":"Proyecciones anuales · escenario {growth}","fr":"Projections annuelles · scénario {growth}","de":"Jährliche Projektionen · {growth} Szenario","pt":"Projeções anuais · cenário {growth}","it":"Proiezioni annuali · scenario {growth}","nl":"Jaarprognoses · {growth} scenario","tr":"Yıllık projeksiyonlar · {growth} senaryosu","uk":"Річні прогнози · сценарій {growth}","ru":"Годовые прогнозы · сценарий {growth}","ar":"توقعات سنوية · سيناريو {growth}","hi":"वार्षिक अनुमान · {growth} परिदृश्य","bn":"বার্ষিক প্রক্ষেপণ · {growth} পরিদৃশ্য","zh":"年度预测 · {growth} 情景","ja":"年間予測 · {growth} シナリオ","id":"Proyeksi tahunan · skenario {growth}"},
    "preview.unit_econ_title": {"es":"Unit Economics","fr":"Unit economics","de":"Unit Economics","pt":"Unit economics","it":"Unit economics","nl":"Unit economics","tr":"Birim ekonomisi","uk":"Юніт-економіка","ru":"Юнит-экономика","ar":"اقتصاديات الوحدة","hi":"यूनिट इकोनॉमिक्स","bn":"ইউনিট ইকোনমিক্স","zh":"单位经济","ja":"ユニットエコノミクス","id":"Unit economics"},
    "preview.unit_econ_sub": {"es":"CAC · LTV · Período de recuperación","fr":"CAC · LTV · Période de récupération","de":"CAC · LTV · Payback-Zeit","pt":"CAC · LTV · Período de payback","it":"CAC · LTV · Periodo di payback","nl":"CAC · LTV · Terugverdientijd","tr":"CAC · LTV · Geri ödeme süresi","uk":"CAC · LTV · Період окупності","ru":"CAC · LTV · Период окупаемости","ar":"CAC · LTV · فترة الاسترداد","hi":"CAC · LTV · पेबैक अवधि","bn":"CAC · LTV · পেব্যাক সময়","zh":"CAC · LTV · 回收期","ja":"CAC · LTV · 投資回収期間","id":"CAC · LTV · Periode payback"},
    "preview.pro_only_badge": {"es":"Solo Pro","fr":"Pro uniquement","de":"Nur Pro","pt":"Apenas Pro","it":"Solo Pro","nl":"Alleen Pro","tr":"Yalnızca Pro","uk":"Лише Pro","ru":"Только Pro","ar":"Pro فقط","hi":"केवल Pro","bn":"শুধু Pro","zh":"仅 Pro","ja":"Pro 限定","id":"Khusus Pro"},
    "preview.upgrade_title": {"es":"Desbloquea tu modelo financiero completo","fr":"Débloquez votre modèle financier complet","de":"Schalte dein vollständiges Finanzmodell frei","pt":"Desbloqueie seu modelo financeiro completo","it":"Sblocca il tuo modello finanziario completo","nl":"Ontgrendel je volledige financiële model","tr":"Tam finansal modelinizi açın","uk":"Розблокуйте свою повну фінансову модель","ru":"Разблокируйте полную финансовую модель","ar":"افتح نموذجك المالي الكامل","hi":"अपना पूरा वित्तीय मॉडल अनलॉक करें","bn":"আপনার পূর্ণ আর্থিক মডেল আনলক করুন","zh":"解锁你的完整财务模型","ja":"完全な財務モデルをアンロック","id":"Buka kunci model keuangan lengkap Anda"},
    "preview.upgrade_body": {"es":"Gráficos interactivos, unit economics, narrativa de financiación, comparación de escenarios, cap table, cada fórmula con tus números y el archivo Excel poblado.","fr":"Graphiques interactifs, unit economics, récit d'investissement, comparaison de scénarios, table de capitalisation, toutes les formules avec vos chiffres, et le fichier Excel pré-rempli.","de":"Interaktive Charts, Unit Economics, Finanzierungsnarrativ, Szenarienvergleich, Cap Table, jede Formel mit deinen Zahlen und die gefüllte Excel-Datei.","pt":"Gráficos interativos, unit economics, narrativa de captação, comparação de cenários, cap table, cada fórmula com seus números e o arquivo Excel preenchido.","it":"Grafici interattivi, unit economics, narrativa di raccolta, confronto di scenari, cap table, ogni formula con i tuoi numeri e il file Excel popolato.","nl":"Interactieve grafieken, unit economics, fundraising-narrative, scenariovergelijking, cap table, elke formule met jouw cijfers en het gevulde Excel-bestand.","tr":"Etkileşimli grafikler, birim ekonomisi, finansman anlatısı, senaryo karşılaştırması, sermaye tablosu, her formül kendi rakamlarınızla ve doldurulmuş Excel dosyası.","uk":"Інтерактивні графіки, юніт-економіка, наратив фінансування, порівняння сценаріїв, cap table, кожна формула з вашими числами та заповнений файл Excel.","ru":"Интерактивные графики, юнит-экономика, нарратив финансирования, сравнение сценариев, cap table, каждая формула с вашими числами и заполненный Excel.","ar":"رسوم تفاعلية، اقتصاديات الوحدة، سرد التمويل، مقارنة السيناريوهات، جدول رأس المال، كل صيغة مع أرقامك، وملف Excel معبأ.","hi":"इंटरैक्टिव चार्ट, यूनिट इकोनॉमिक्स, फंडिंग नैरेटिव, परिदृश्य तुलना, कैप टेबल, आपके आँकड़ों के साथ हर फ़ॉर्मूला और भरी हुई Excel फ़ाइल।","bn":"ইন্টারেক্টিভ চার্ট, ইউনিট ইকোনমিক্স, ফান্ডিং ন্যারেটিভ, পরিদৃশ্য তুলনা, ক্যাপ টেবিল, আপনার সংখ্যা সহ প্রতিটি ফর্মুলা এবং পূরণ করা Excel ফাইল।","zh":"交互式图表、单位经济、融资叙述、情景对比、股权结构表、所有公式带你的数据,以及填充好的 Excel 文件。","ja":"インタラクティブなチャート、ユニットエコノミクス、資金調達ナラティブ、シナリオ比較、キャップテーブル、あなたの数値で計算されたすべての数式、入力済み Excel ファイル。","id":"Grafik interaktif, unit economics, narasi pendanaan, perbandingan skenario, cap table, setiap rumus dengan angka Anda, dan file Excel yang terisi."},
    "preview.upgrade_cancel": {"es":"Cancela cuando quieras · Sin compromiso","fr":"Annulez quand vous voulez · Sans engagement","de":"Jederzeit kündbar · Keine Verpflichtung","pt":"Cancele a qualquer momento · Sem compromisso","it":"Disdici quando vuoi · Nessun impegno","nl":"Altijd opzegbaar · Geen verplichting","tr":"İstediğin zaman iptal · Taahhüt yok","uk":"Скасуйте будь-коли · Без зобов'язань","ru":"Отмена в любой момент · Без обязательств","ar":"إلغاء في أي وقت · بدون التزام","hi":"कभी भी रद्द करें · कोई प्रतिबद्धता नहीं","bn":"যেকোনো সময় বাতিল · কোনো অঙ্গীকার নয়","zh":"随时取消 · 无承诺","ja":"いつでもキャンセル · コミットなし","id":"Batalkan kapan saja · Tanpa komitmen"},
    "preview.upgrade_see_included": {"es":"Ver lo que se incluye →","fr":"Voir ce qui est inclus →","de":"Sieh, was enthalten ist →","pt":"Veja o que está incluso →","it":"Vedi cosa è incluso →","nl":"Zie wat is inbegrepen →","tr":"Neler dahil bak →","uk":"Подивитися, що входить →","ru":"Что входит →","ar":"شاهد ما يتضمنه →","hi":"देखें क्या-क्या शामिल है →","bn":"কী অন্তর্ভুক্ত দেখুন →","zh":"查看包含内容 →","ja":"含まれる内容を見る →","id":"Lihat apa yang termasuk →"},
    "preview.sources_uses_title": {"es":"Fuentes y usos","fr":"Sources et emplois","de":"Mittel & Verwendung","pt":"Fontes e usos","it":"Fonti e impieghi","nl":"Sources & uses","tr":"Kaynaklar ve kullanım","uk":"Джерела і використання","ru":"Источники и использование","ar":"المصادر والاستخدامات","hi":"स्रोत और उपयोग","bn":"উৎস ও ব্যবহার","zh":"资金来源与用途","ja":"資金調達と使途","id":"Sumber & penggunaan"},
    "preview.sources_uses_sub": {"es":"De dónde viene el capital y a dónde va — desde tu asignación de Q10.","fr":"D'où vient le capital et où il va — extrait de votre allocation Q10.","de":"Woher das Kapital kommt und wohin es geht — aus deiner Q10-Allokation.","pt":"De onde vem o capital e para onde vai — a partir da sua alocação Q10.","it":"Da dove viene il capitale e dove va — dalla tua allocazione Q10.","nl":"Waar het kapitaal vandaan komt en waar het naartoe gaat — uit je Q10-allocatie.","tr":"Sermaye nereden geliyor ve nereye gidiyor — Q10 dağılımınızdan.","uk":"Звідки капітал і куди йде — з вашого розподілу Q10.","ru":"Откуда капитал и куда идёт — из вашего распределения Q10.","ar":"من أين يأتي رأس المال وأين يذهب — من توزيع Q10.","hi":"पूँजी कहाँ से आती है और कहाँ जाती है — आपके Q10 आवंटन से।","bn":"মূলধন কোথা থেকে আসে এবং কোথায় যায় — আপনার Q10 বরাদ্দ থেকে।","zh":"资金从哪里来、到哪里去 — 来自你的 Q10 分配。","ja":"資本がどこから来てどこへ行くか — Q10 の配分から。","id":"Dari mana modal datang dan ke mana — dari alokasi Q10 Anda."},

    # ===== FULL =====
    "full.full_model_pro": {"es":"Modelo completo — Pro","fr":"Modèle complet — Pro","de":"Vollständiges Modell — Pro","pt":"Modelo completo — Pro","it":"Modello completo — Pro","nl":"Volledig model — Pro","tr":"Tam model — Pro","uk":"Повна модель — Pro","ru":"Полная модель — Pro","ar":"النموذج الكامل — Pro","hi":"पूर्ण मॉडल — Pro","bn":"পূর্ণ মডেল — Pro","zh":"完整模型 — Pro","ja":"完全モデル — Pro","id":"Model lengkap — Pro"},
    "full.ai_insights_label": {"es":"Insights del modelo (IA)","fr":"Insights du modèle IA","de":"KI-Modell-Insights","pt":"Insights do modelo IA","it":"Insights del modello IA","nl":"AI-modelinzichten","tr":"AI model içgörüleri","uk":"Інсайти моделі ШІ","ru":"Инсайты модели ИИ","ar":"رؤى نموذج الذكاء الاصطناعي","hi":"AI मॉडल इनसाइट्स","bn":"AI মডেল ইনসাইট","zh":"AI 模型洞察","ja":"AI モデル洞察","id":"Wawasan model AI"},
    "full.income_statement": {"es":"Estado de resultados","fr":"Compte de résultat","de":"Gewinn- und Verlustrechnung","pt":"Demonstração de resultados","it":"Conto economico","nl":"Resultatenrekening","tr":"Gelir tablosu","uk":"Звіт про прибутки та збитки","ru":"Отчёт о прибылях и убытках","ar":"قائمة الدخل","hi":"आय विवरण","bn":"আয় বিবরণী","zh":"损益表","ja":"損益計算書","id":"Laporan laba rugi"},
    "full.income_statement_sub": {"es":"Proyecciones anuales a {years} años · escenario {growth}","fr":"Projections annuelles sur {years} ans · scénario {growth}","de":"Jährliche Projektionen über {years} Jahre · {growth} Szenario","pt":"Projeções anuais de {years} anos · cenário {growth}","it":"Proiezioni annuali a {years} anni · scenario {growth}","nl":"Jaarprognoses over {years} jaar · {growth} scenario","tr":"{years} yıllık yıllık projeksiyonlar · {growth} senaryosu","uk":"Річні прогнози на {years} років · сценарій {growth}","ru":"Годовые прогнозы на {years} лет · сценарий {growth}","ar":"توقعات سنوية لـ {years} سنوات · سيناريو {growth}","hi":"{years}-वर्षीय वार्षिक अनुमान · {growth} परिदृश्य","bn":"{years}-বছরের বার্ষিক প্রক্ষেপণ · {growth} পরিদৃশ্য","zh":"{years} 年年度预测 · {growth} 情景","ja":"{years} 年間予測 · {growth} シナリオ","id":"Proyeksi tahunan {years} tahun · skenario {growth}"},
    "full.unit_econ_title": {"es":"Unit Economics","fr":"Unit economics","de":"Unit Economics","pt":"Unit economics","it":"Unit economics","nl":"Unit economics","tr":"Birim ekonomisi","uk":"Юніт-економіка","ru":"Юнит-экономика","ar":"اقتصاديات الوحدة","hi":"यूनिट इकोनॉमिक्स","bn":"ইউনিট ইকোনমিক্স","zh":"单位经济","ja":"ユニットエコノミクス","id":"Unit economics"},
    "full.unit_econ_sub": {"es":"Métricas clave para salud del negocio y solidez ante inversores","fr":"Métriques clés pour la santé de l'entreprise et la solidité face aux investisseurs","de":"Kernkennzahlen für Unternehmensgesundheit und Investor-Readiness","pt":"Métricas chave para saúde do negócio e prontidão para investidores","it":"Metriche chiave per salute del business e prontezza per investitori","nl":"Kerncijfers voor bedrijfsgezondheid en investeerderbereidheid","tr":"İşin sağlığı ve yatırımcı hazırlığı için temel metrikler","uk":"Ключові метрики здоров'я бізнесу та готовності до інвесторів","ru":"Ключевые метрики здоровья бизнеса и готовности к инвесторам","ar":"المقاييس الأساسية لصحة العمل والاستعداد للمستثمرين","hi":"व्यवसाय की सेहत और निवेशक तत्परता के मूल मेट्रिक्स","bn":"ব্যবসায়িক স্বাস্থ্য এবং বিনিয়োগকারী প্রস্তুতির মূল মেট্রিক্স","zh":"业务健康度与投资人就绪度的核心指标","ja":"事業の健全性と投資家への準備態勢に関する主要指標","id":"Metrik inti untuk kesehatan bisnis dan kesiapan investor"},
    "full.scenarios_title": {"es":"Comparación de escenarios","fr":"Comparaison de scénarios","de":"Szenarienvergleich","pt":"Comparação de cenários","it":"Confronto scenari","nl":"Scenariovergelijking","tr":"Senaryo karşılaştırması","uk":"Порівняння сценаріїв","ru":"Сравнение сценариев","ar":"مقارنة السيناريوهات","hi":"परिदृश्य तुलना","bn":"পরিদৃশ্য তুলনা","zh":"情景对比","ja":"シナリオ比較","id":"Perbandingan skenario"},
    "full.scenarios_sub": {"es":"Conservador vs Base vs Agresivo en métricas clave","fr":"Conservateur vs Base vs Agressif sur les métriques clés","de":"Konservativ vs Base vs Aggressiv über Schlüsselmetriken","pt":"Conservador vs Base vs Agressivo nas métricas chave","it":"Conservativo vs Base vs Aggressivo sulle metriche chiave","nl":"Conservatief vs Base vs Agressief over kerncijfers","tr":"Muhafazakâr vs Temel vs Agresif anahtar metriklerde","uk":"Консервативний проти Базового проти Агресивного у ключових метриках","ru":"Консервативный vs Базовый vs Агрессивный по ключевым метрикам","ar":"محافظ مقابل أساسي مقابل طموح عبر المقاييس الرئيسية","hi":"मुख्य मेट्रिक्स पर रूढ़िवादी बनाम बेस बनाम आक्रामक","bn":"মূল মেট্রিক্সে রক্ষণশীল বনাম বেস বনাম আগ্রাসী","zh":"保守 vs 基础 vs 激进 在关键指标上的对比","ja":"主要指標における保守 vs ベース vs 積極の比較","id":"Konservatif vs Dasar vs Agresif pada metrik utama"},
    "full.cap_table_title": {"es":"Cap Table","fr":"Cap table","de":"Cap Table","pt":"Cap table","it":"Cap table","nl":"Cap table","tr":"Sermaye yapısı","uk":"Cap table","ru":"Cap table","ar":"جدول رأس المال","hi":"कैप टेबल","bn":"ক্যাপ টেবিল","zh":"股权结构表","ja":"キャップテーブル","id":"Cap table"},
    "full.cap_table_sub": {"es":"Propiedad pre / post-ronda para esta ronda.","fr":"Propriété pré / post-levée pour cette levée.","de":"Eigentum vor / nach der Runde für diese Runde.","pt":"Propriedade pré / pós-rodada para esta rodada.","it":"Proprietà pre / post-round per questo round.","nl":"Eigendom voor / na deze ronde.","tr":"Bu yatırım turunun yatırım öncesi / sonrası sahipliği.","uk":"Власність до / після раунду для цього раунду.","ru":"Владение до / после раунда для этого раунда.","ar":"الملكية قبل وبعد جولة الاستثمار الحالية.","hi":"इस राउंड के लिए राउंड-पूर्व / राउंड-बाद का स्वामित्व।","bn":"এই রাউন্ডের জন্য রাউন্ড-পূর্ব / পরবর্তী মালিকানা।","zh":"本轮的融资前 / 后股权。","ja":"今回ラウンドのラウンド前 / 後の所有権。","id":"Kepemilikan pra / pasca-ronde untuk ronde ini."},
    "full.waterfall_title": {"es":"Cascada de dilución multi-ronda","fr":"Cascade de dilution multi-rondes","de":"Mehrjährige Verwässerungskaskade","pt":"Cascata de diluição multi-rodada","it":"Waterfall di diluizione multi-round","nl":"Multi-ronde verwateringswaterfall","tr":"Çok turlu seyrelme şelalesi","uk":"Каскад розмиття по раундах","ru":"Каскад размытия по раундам","ar":"شلال التخفيف عبر الجولات","hi":"बहु-राउंड डाइल्यूशन वाटरफ़ॉल","bn":"মাল্টি-রাউন্ড ডাইলিউশন ওয়াটারফল","zh":"多轮股权稀释瀑布","ja":"複数ラウンドの希薄化ウォーターフォール","id":"Waterfall dilusi multi-ronde"},
    "full.waterfall_sub": {"es":"Edita splits pre-seed y rondas futuras proyectadas — la tabla muestra la dilución del fundador en cada etapa, incluyendo refrescos de ESOP.","fr":"Modifiez les splits pre-seed et les rondes futures projetées — le tableau montre la dilution du fondateur à chaque étape, y compris les refresh d'ESOP.","de":"Bearbeite Pre-Seed-Splits und projizierte zukünftige Runden — die Tabelle zeigt die Gründerverwässerung in jeder Stufe inkl. ESOP-Refreshes.","pt":"Edite splits pre-seed e rodadas futuras projetadas — a tabela mostra a diluição do fundador em cada estágio, incluindo refreshes de ESOP.","it":"Modifica gli split pre-seed e i round futuri proiettati — la tabella mostra la diluizione del fondatore in ogni fase, inclusi i refresh di ESOP.","nl":"Bewerk pre-seed splits en geprojecteerde toekomstige rondes — de tabel toont de oprichter-verwatering per fase, inclusief ESOP-refreshes.","tr":"Pre-seed ayrımlarını ve projeksiyon turlarını düzenleyin — tablo, ESOP yenilemeleri dahil her aşamada kurucu seyrelmesini gösterir.","uk":"Редагуйте pre-seed розподіли та проєктовані майбутні раунди — таблиця показує розмиття засновника на кожному етапі, включаючи оновлення ESOP.","ru":"Редактируйте pre-seed разбивки и проектируемые будущие раунды — таблица показывает размывание основателя на каждом этапе, включая обновления ESOP.","ar":"حرّر تقسيمات pre-seed والجولات المستقبلية المتوقعة — يعرض الجدول تخفيف ملكية المؤسس في كل مرحلة بما في ذلك تحديثات ESOP.","hi":"प्री-सीड स्प्लिट्स और प्रोजेक्टेड भविष्य के राउंड्स संपादित करें — टेबल हर स्टेज पर फाउंडर डाइल्यूशन दिखाती है, जिसमें ESOP रिफ्रेश शामिल हैं।","bn":"প্রি-সিড স্প্লিট এবং প্রক্ষেপিত ভবিষ্যৎ রাউন্ড সম্পাদনা করুন — টেবিল প্রতিটি পর্যায়ে ফাউন্ডার ডাইলিউশন দেখায়, ESOP রিফ্রেশ সহ।","zh":"编辑 pre-seed 分股和未来融资轮预测 — 表格显示每一阶段的创始人股权稀释,包括 ESOP 增发。","ja":"プレシード分配と将来のラウンド予測を編集 — テーブルは ESOP リフレッシュを含む各段階の創業者希薄化を示します。","id":"Edit pembagian pre-seed dan ronde mendatang yang diproyeksikan — tabel menunjukkan dilusi founder di setiap tahap, termasuk refresh ESOP."},
    "full.valuation_title": {"es":"Valoración (DCF)","fr":"Valorisation (DCF)","de":"Bewertung (DCF)","pt":"Valuation (DCF)","it":"Valutazione (DCF)","nl":"Waardering (DCF)","tr":"Değerleme (DCF)","uk":"Оцінка (DCF)","ru":"Оценка (DCF)","ar":"التقييم (DCF)","hi":"मूल्यांकन (DCF)","bn":"মূল্যায়ন (DCF)","zh":"估值 (DCF)","ja":"バリュエーション (DCF)","id":"Valuasi (DCF)"},
    "full.valuation_sub": {"es":"Construye tu tasa de descuento desde CAPM + costo de deuda, luego ve el DCF año a año y una matriz de sensibilidad WACC × crecimiento terminal.","fr":"Construisez votre taux d'actualisation depuis CAPM + coût de la dette, puis voyez le DCF année par année et une matrice de sensibilité WACC × croissance terminale.","de":"Baue deinen Diskontsatz aus CAPM + Fremdkapitalkosten, dann sieh den jährlichen DCF und eine Sensitivitätsmatrix WACC × terminale Wachstumsrate.","pt":"Construa sua taxa de desconto a partir de CAPM + custo de dívida, depois veja o DCF ano a ano e uma matriz de sensibilidade WACC × crescimento terminal.","it":"Costruisci il tuo tasso di sconto da CAPM + costo del debito, poi vedi il DCF anno per anno e una matrice di sensibilità WACC × crescita terminale.","nl":"Bouw je discontovoet uit CAPM + kosten van schuld, en zie de jaarlijkse DCF + WACC × terminale-groei gevoeligheidsmatrix.","tr":"İskonto oranınızı CAPM + borç maliyetinden oluşturun; ardından yıldan yıla DCF ve WACC × terminal büyüme duyarlılık matrisini görün.","uk":"Побудуйте ставку дисконтування з CAPM + вартість боргу, потім подивіться DCF рік за роком і матрицю чутливості WACC × термінальне зростання.","ru":"Постройте ставку дисконтирования из CAPM + стоимость долга, затем просмотрите DCF по годам и матрицу чувствительности WACC × терминальный рост.","ar":"ابنِ معدل الخصم من CAPM + تكلفة الدين، ثم شاهد DCF سنة بسنة ومصفوفة حساسية WACC × النمو النهائي.","hi":"CAPM + ऋण लागत से अपनी छूट दर बनाएँ, फिर साल-दर-साल DCF और WACC × टर्मिनल वृद्धि की संवेदनशीलता मैट्रिक्स देखें।","bn":"CAPM + ঋণ খরচ থেকে আপনার ডিসকাউন্ট রেট তৈরি করুন, তারপর বছর-অনুযায়ী DCF এবং WACC × টার্মিনাল বৃদ্ধির সংবেদনশীলতা ম্যাট্রিক্স দেখুন।","zh":"基于 CAPM + 债务成本构建你的折现率,然后查看逐年 DCF 和 WACC × 终值增长的敏感性矩阵。","ja":"CAPM + 負債コストから割引率を構築し、年次 DCF と WACC × ターミナル成長の感応度マトリクスを確認。","id":"Bangun discount rate dari CAPM + biaya hutang, lalu lihat DCF tahun demi tahun dan matriks sensitivitas WACC × pertumbuhan terminal."},
    "full.pro_wacc_title": {"es":"Construcción WACC Pro","fr":"Construction WACC Pro","de":"Pro WACC-Aufbau","pt":"Construção WACC Pro","it":"Costruzione WACC Pro","nl":"Pro WACC-opbouw","tr":"Pro WACC inşası","uk":"Pro збірка WACC","ru":"Pro построение WACC","ar":"بناء WACC في Pro","hi":"Pro WACC बिल्ड-अप","bn":"Pro WACC বিল্ড-আপ","zh":"Pro WACC 构建","ja":"Pro WACC 構築","id":"Pembangunan WACC Pro"},
    "full.pro_wacc_sub": {"es":"Refina la tasa de descuento desde CAPM + costo de deuda; la tabla DCF y la matriz de sensibilidad recalculan en vivo.","fr":"Affinez le taux d'actualisation depuis CAPM + coût de la dette ; le tableau DCF et la matrice de sensibilité recalculent en direct.","de":"Verfeinere den Diskontsatz aus CAPM + Fremdkapitalkosten; DCF-Tabelle und Sensitivitätsmatrix berechnen live neu.","pt":"Refine a taxa de desconto a partir de CAPM + custo de dívida; a tabela DCF e a matriz de sensibilidade recalculam ao vivo.","it":"Affina il tasso di sconto da CAPM + costo del debito; la tabella DCF e la matrice di sensibilità si ricalcolano in tempo reale.","nl":"Verfijn de discontovoet vanuit CAPM + kosten van schuld; DCF-tabel en gevoeligheidsmatrix herberekenen live.","tr":"İskonto oranını CAPM + borç maliyetinden iyileştirin; DCF tablosu ve duyarlılık matrisi canlı yeniden hesaplanır.","uk":"Уточніть ставку дисконтування з CAPM + вартість боргу; таблиця DCF та матриця чутливості перераховуються в реальному часі.","ru":"Уточните ставку дисконтирования из CAPM + стоимость долга; таблица DCF и матрица чувствительности пересчитываются в реальном времени.","ar":"حسّن معدل الخصم من CAPM + تكلفة الدين؛ يعاد حساب جدول DCF ومصفوفة الحساسية مباشرة.","hi":"CAPM + ऋण लागत से डिस्काउंट रेट परिष्कृत करें; DCF टेबल और संवेदनशीलता मैट्रिक्स लाइव पुनर्गणित होते हैं।","bn":"CAPM + ঋণ খরচ থেকে ডিসকাউন্ট রেট পরিমার্জন করুন; DCF টেবিল এবং সংবেদনশীলতা ম্যাট্রিক্স লাইভ পুনঃগণনা হয়।","zh":"基于 CAPM + 债务成本细化折现率;DCF 表与敏感性矩阵实时重新计算。","ja":"CAPM + 負債コストから割引率を改良。DCF 表と感応度マトリクスがライブ再計算されます。","id":"Sempurnakan discount rate dari CAPM + biaya hutang; tabel DCF dan matriks sensitivitas dihitung ulang langsung."},
    "full.sensitivity_title": {"es":"Análisis de sensibilidad","fr":"Analyse de sensibilité","de":"Sensitivitätsanalyse","pt":"Análise de sensibilidade","it":"Analisi di sensibilità","nl":"Gevoeligheidsanalyse","tr":"Duyarlılık analizi","uk":"Аналіз чутливості","ru":"Анализ чувствительности","ar":"تحليل الحساسية","hi":"संवेदनशीलता विश्लेषण","bn":"সংবেদনশীলতা বিশ্লেষণ","zh":"敏感性分析","ja":"感応度分析","id":"Analisis sensitivitas"},
    "full.sensitivity_sub": {"es":"Estresa cada input — burn, CAC, churn, precios, crecimiento, runway — y ve el impacto en vivo sobre ARR del Año 3, EBITDA, runway y unit economics.","fr":"Stress-testez chaque input — burn, CAC, churn, prix, croissance, runway — et voyez l'impact en direct sur l'ARR Année 3, l'EBITDA, le runway et les unit economics.","de":"Stress-teste jedes Input — Burn, CAC, Churn, Preise, Wachstum, Runway — und sieh den Live-Effekt auf Year-3 ARR, EBITDA, Runway und Unit Economics.","pt":"Faça stress test em cada input — burn, CAC, churn, preços, crescimento, runway — e veja o impacto ao vivo no ARR Ano 3, EBITDA, runway e unit economics.","it":"Stress-test ogni input — burn, CAC, churn, prezzi, crescita, runway — e vedi l'impatto live su ARR Anno 3, EBITDA, runway e unit economics.","nl":"Stress-test elke input — burn, CAC, churn, prijzen, groei, runway — en zie de live-impact op Year-3 ARR, EBITDA, runway en unit economics.","tr":"Her girdiyi stres testi yapın — burn, CAC, churn, fiyatlar, büyüme, runway — ve 3. yıl ARR, EBITDA, runway ve birim ekonomisi üzerindeki canlı etkiyi görün.","uk":"Стрес-тест кожного вхідного значення — burn, CAC, churn, ціни, зростання, runway — і подивіться вплив у реальному часі на ARR 3-го року, EBITDA, runway та юніт-економіку.","ru":"Стресс-тест каждого входа — burn, CAC, churn, цены, рост, runway — и просмотр живого воздействия на ARR 3-го года, EBITDA, runway и юнит-экономику.","ar":"اختبر كل مدخل تحت الضغط — burn، CAC، churn، الأسعار، النمو، runway — وشاهد التأثير المباشر على ARR السنة 3 وEBITDA وrunway واقتصاديات الوحدة.","hi":"हर इनपुट का स्ट्रेस-टेस्ट करें — burn, CAC, churn, प्राइसिंग, ग्रोथ, runway — और वर्ष-3 ARR, EBITDA, runway और यूनिट इकोनॉमिक्स पर लाइव प्रभाव देखें।","bn":"প্রতিটি ইনপুট স্ট্রেস-টেস্ট করুন — burn, CAC, churn, প্রাইসিং, গ্রোথ, runway — এবং Year-3 ARR, EBITDA, runway এবং ইউনিট ইকোনমিক্সে লাইভ প্রভাব দেখুন।","zh":"对每个输入做压力测试 — 烧钱、CAC、流失、定价、增长、runway — 查看对第 3 年 ARR、EBITDA、runway 和单位经济的实时影响。","ja":"各入力をストレステスト — バーン、CAC、チャーン、価格、成長、ランウェイ — し、3 年目 ARR、EBITDA、ランウェイ、ユニットエコノミクスへのライブ影響を確認。","id":"Stress-test setiap input — burn, CAC, churn, harga, pertumbuhan, runway — dan lihat dampak langsung pada ARR Tahun 3, EBITDA, runway, dan unit economics."},
    "full.calculations_title": {"es":"Cálculos","fr":"Calculs","de":"Berechnungen","pt":"Cálculos","it":"Calcoli","nl":"Berekeningen","tr":"Hesaplamalar","uk":"Розрахунки","ru":"Расчёты","ar":"الحسابات","hi":"गणनाएँ","bn":"গণনা","zh":"计算","ja":"計算","id":"Perhitungan"},
    "full.calculations_sub": {"es":"Cada fórmula del modelo, con tus inputs aplicados","fr":"Chaque formule du modèle, avec vos entrées appliquées","de":"Jede Formel im Modell mit deinen Eingaben eingesetzt","pt":"Cada fórmula do modelo, com seus inputs aplicados","it":"Ogni formula del modello con i tuoi input applicati","nl":"Elke formule in het model, met jouw inputs ingevoerd","tr":"Modeldeki her formül, kendi girdileriniz uygulanmış","uk":"Кожна формула моделі з вашими введеними даними","ru":"Каждая формула модели с вашими входами","ar":"كل صيغة في النموذج مع مدخلاتك مُطبّقة","hi":"मॉडल के पीछे हर फ़ॉर्मूला, आपके इनपुट लागू किए गए","bn":"মডেলের প্রতিটি ফর্মুলা, আপনার ইনপুট প্রয়োগ করা","zh":"模型中的每个公式,带入你的输入","ja":"モデルのすべての数式に、あなたの入力を当てはめて表示","id":"Setiap rumus dalam model, dengan input Anda diterapkan"},
    "full.cash_flow_title": {"es":"Estado de flujo de caja","fr":"Tableau de flux de trésorerie","de":"Kapitalflussrechnung","pt":"Demonstração de fluxo de caixa","it":"Rendiconto finanziario","nl":"Kasstroomoverzicht","tr":"Nakit akış tablosu","uk":"Звіт про рух грошових коштів","ru":"Отчёт о движении денежных средств","ar":"قائمة التدفقات النقدية","hi":"कैश फ़्लो स्टेटमेंट","bn":"ক্যাশ ফ্লো স্টেটমেন্ট","zh":"现金流量表","ja":"キャッシュ・フロー計算書","id":"Laporan arus kas"},
    "full.cash_flow_sub": {"es":"Método indirecto · {years} años · operativo + inversión + financiación","fr":"Méthode indirecte · {years} ans · exploitation + investissement + financement","de":"Indirekte Methode · {years} Jahre · operativ + Investition + Finanzierung","pt":"Método indireto · {years} anos · operacional + investimento + financiamento","it":"Metodo indiretto · {years} anni · operativo + investimento + finanziamento","nl":"Indirecte methode · {years} jaar · operationeel + investering + financiering","tr":"Dolaylı yöntem · {years} yıl · işletme + yatırım + finansman","uk":"Непрямий метод · {years} років · операційний + інвестиційний + фінансовий","ru":"Косвенный метод · {years} лет · операционный + инвестиционный + финансовый","ar":"الطريقة غير المباشرة · {years} سنوات · تشغيلي + استثماري + تمويلي","hi":"अप्रत्यक्ष विधि · {years} वर्ष · परिचालन + निवेश + वित्तपोषण","bn":"পরোক্ষ পদ্ধতি · {years} বছর · পরিচালন + বিনিয়োগ + অর্থায়ন","zh":"间接法 · {years} 年 · 经营 + 投资 + 筹资","ja":"間接法 · {years} 年間 · 営業 + 投資 + 財務","id":"Metode tidak langsung · {years} tahun · operasi + investasi + pendanaan"},
    "full.sources_uses_sub": {"es":"Capital que entra vs capital que sale — directo desde tu asignación de Q10. Debe balancear.","fr":"Capital entrant vs capital sortant — directement de votre allocation Q10. Doit s'équilibrer.","de":"Eingehendes vs ausgehendes Kapital — direkt aus deiner Q10-Allokation. Muss ausgeglichen sein.","pt":"Capital entrando vs capital saindo — direto da sua alocação Q10. Deve balancear.","it":"Capitale in entrata vs capitale in uscita — direttamente dalla tua allocazione Q10. Deve bilanciarsi.","nl":"Inkomend kapitaal vs uitgaand kapitaal — direct uit je Q10-allocatie. Moet in evenwicht zijn.","tr":"Giren sermaye karşı çıkan sermaye — doğrudan Q10 dağılımınızdan. Dengelenmelidir.","uk":"Капітал, що надходить vs капітал, що виходить — безпосередньо з вашого Q10 розподілу. Має балансуватися.","ru":"Поступающий капитал vs уходящий капитал — напрямую из вашего распределения Q10. Должен балансироваться.","ar":"رأس المال الداخل مقابل الخارج — مباشرة من توزيع Q10. يجب أن يتوازنا.","hi":"आने वाली पूँजी बनाम जाने वाली पूँजी — सीधे आपके Q10 आवंटन से। संतुलित होनी चाहिए।","bn":"আসা মূলধন বনাম যাওয়া মূলধন — সরাসরি আপনার Q10 বরাদ্দ থেকে। সমান হতে হবে।","zh":"流入资本 vs 流出资本 — 直接来自你的 Q10 分配。必须平衡。","ja":"流入資本と流出資本 — Q10 配分から直接。バランスが取れている必要があります。","id":"Modal masuk vs modal keluar — langsung dari alokasi Q10 Anda. Harus seimbang."},

    # ===== PRICING =====
    "pricing.headline_a": {"es":"Precios simples.","fr":"Tarifs simples.","de":"Einfache Preise.","pt":"Preços simples.","it":"Prezzi semplici.","nl":"Eenvoudige prijzen.","tr":"Basit fiyatlandırma.","uk":"Прості ціни.","ru":"Простые цены.","ar":"تسعير بسيط.","hi":"सरल मूल्य निर्धारण।","bn":"সহজ মূল্য।","zh":"简单定价。","ja":"シンプルな価格設定。","id":"Harga sederhana."},
    "pricing.headline_b": {"es":"Hechos para fundadores.","fr":"Conçus pour les fondateurs.","de":"Gemacht für Gründer.","pt":"Feito para fundadores.","it":"Pensato per i founder.","nl":"Gemaakt voor founders.","tr":"Kurucular için tasarlandı.","uk":"Створено для засновників.","ru":"Создано для основателей.","ar":"مصمم للمؤسسين.","hi":"फाउंडर के लिए बनाया गया।","bn":"ফাউন্ডারের জন্য নির্মিত।","zh":"为创始人打造。","ja":"創業者向けに設計。","id":"Dibuat untuk founder."},
    "pricing.subheadline": {"es":"Empieza gratis. Actualiza cuando necesites el modelo completo, gráficos, escenarios y descarga Excel.","fr":"Commencez gratuitement. Passez Pro quand vous avez besoin du modèle complet, des graphiques, des scénarios et du téléchargement Excel.","de":"Beginne kostenlos. Upgrade, wenn du das volle Modell, Charts, Szenarien und den Excel-Download brauchst.","pt":"Comece grátis. Faça upgrade quando precisar do modelo completo, gráficos, cenários e download Excel.","it":"Inizia gratis. Passa a Pro quando ti serve il modello completo, grafici, scenari e download Excel.","nl":"Begin gratis. Upgrade wanneer je het volledige model, grafieken, scenario's en Excel-download nodig hebt.","tr":"Ücretsiz başla. Tam modeli, grafikleri, senaryoları ve Excel indirmeyi gerektirdiğinde Pro'ya geç.","uk":"Почніть безкоштовно. Перейдіть на Pro, коли потрібна повна модель, графіки, сценарії та завантаження Excel.","ru":"Начните бесплатно. Перейдите на Pro, когда нужна полная модель, графики, сценарии и скачивание Excel.","ar":"ابدأ مجانًا. ارتقِ إلى Pro عندما تحتاج إلى النموذج الكامل والرسوم والسيناريوهات وتنزيل Excel.","hi":"मुफ़्त शुरू करें। पूरा मॉडल, चार्ट, परिदृश्य और Excel डाउनलोड चाहिए तो अपग्रेड करें।","bn":"ফ্রি শুরু করুন। পূর্ণ মডেল, চার্ট, পরিদৃশ্য এবং Excel ডাউনলোড দরকার হলে আপগ্রেড করুন।","zh":"免费开始。需要完整模型、图表、情景和 Excel 下载时升级。","ja":"無料で開始。完全モデル、チャート、シナリオ、Excel ダウンロードが必要になったらアップグレード。","id":"Mulai gratis. Upgrade saat butuh model lengkap, grafik, skenario, dan unduhan Excel."},
    "pricing.free_title": {"es":"Gratis","fr":"Gratuit","de":"Free","pt":"Grátis","it":"Gratis","nl":"Gratis","tr":"Ücretsiz","uk":"Безкоштовно","ru":"Бесплатно","ar":"مجاني","hi":"मुफ़्त","bn":"ফ্রি","zh":"免费","ja":"無料","id":"Gratis"},
    "pricing.free_subtitle": {"es":"Para siempre, sin tarjeta","fr":"Pour toujours, sans carte","de":"Für immer, ohne Karte","pt":"Para sempre, sem cartão","it":"Per sempre, senza carta","nl":"Voor altijd, geen kaart","tr":"Sonsuza dek, kart gerekmez","uk":"Назавжди, без картки","ru":"Навсегда, без карты","ar":"للأبد، بدون بطاقة","hi":"हमेशा के लिए, बिना कार्ड","bn":"চিরতরে, কার্ড লাগে না","zh":"永久免费,无需信用卡","ja":"永久無料、カード不要","id":"Selamanya, tanpa kartu"},
    "pricing.pro_title": {"es":"Pro","fr":"Pro","de":"Pro","pt":"Pro","it":"Pro","nl":"Pro","tr":"Pro","uk":"Pro","ru":"Pro","ar":"Pro","hi":"Pro","bn":"Pro","zh":"Pro","ja":"Pro","id":"Pro"},
    "pricing.pro_subtitle": {"es":"Todo lo de Gratis, más el modelo completo","fr":"Tout de Gratuit, plus le modèle complet","de":"Alles aus Free, plus das volle Modell","pt":"Tudo do Grátis, mais o modelo completo","it":"Tutto di Gratis, più il modello completo","nl":"Alles van Gratis, plus het volledige model","tr":"Ücretsiz'in tüm özellikleri ve tam model","uk":"Усе з Безкоштовного плюс повна модель","ru":"Всё из Бесплатного плюс полная модель","ar":"كل ميزات الإصدار المجاني، بالإضافة إلى النموذج الكامل","hi":"मुफ़्त की हर सुविधा, साथ ही पूरा मॉडल","bn":"ফ্রি-র সবকিছু, এছাড়াও পূর্ণ মডেল","zh":"包含 Free 所有功能,加上完整模型","ja":"Free のすべて + 完全モデル","id":"Semua fitur Gratis, ditambah model lengkap"},
    "pricing.pro_price_per_mo": {"es":"/mes","fr":"/mois","de":"/Monat","pt":"/mês","it":"/mese","nl":"/mnd","tr":"/ay","uk":"/міс","ru":"/мес","ar":"/شهر","hi":"/माह","bn":"/মাস","zh":"/月","ja":"/月","id":"/bulan"},
    "pricing.cta_free": {"es":"Empezar gratis","fr":"Commencer gratuitement","de":"Kostenlos starten","pt":"Começar grátis","it":"Inizia gratis","nl":"Gratis beginnen","tr":"Ücretsiz başla","uk":"Почати безкоштовно","ru":"Начать бесплатно","ar":"ابدأ مجانًا","hi":"मुफ़्त शुरू करें","bn":"ফ্রি শুরু করুন","zh":"免费开始","ja":"無料で開始","id":"Mulai gratis"},
    "pricing.cta_pro": {"es":"Obtener Pro","fr":"Passer Pro","de":"Pro holen","pt":"Obter Pro","it":"Passa a Pro","nl":"Pro nemen","tr":"Pro'ya geç","uk":"Отримати Pro","ru":"Получить Pro","ar":"الحصول على Pro","hi":"Pro लें","bn":"Pro নিন","zh":"升级 Pro","ja":"Pro を購入","id":"Dapatkan Pro"},
    "pricing.cancel_anytime": {"es":"Cancela cuando quieras","fr":"Annulez quand vous voulez","de":"Jederzeit kündbar","pt":"Cancele quando quiser","it":"Disdici quando vuoi","nl":"Altijd opzegbaar","tr":"İstediğin zaman iptal","uk":"Скасуйте будь-коли","ru":"Отмена в любой момент","ar":"إلغاء في أي وقت","hi":"कभी भी रद्द करें","bn":"যেকোনো সময় বাতিল","zh":"随时取消","ja":"いつでもキャンセル","id":"Batalkan kapan saja"},
    "pricing.faq_title": {"es":"Preguntas frecuentes","fr":"Questions fréquentes","de":"Häufig gestellte Fragen","pt":"Perguntas frequentes","it":"Domande frequenti","nl":"Veelgestelde vragen","tr":"Sıkça sorulanlar","uk":"Часті питання","ru":"Часто задаваемые вопросы","ar":"الأسئلة الشائعة","hi":"अक्सर पूछे जाने वाले","bn":"প্রায়ই জিজ্ঞাসিত","zh":"常见问题","ja":"よくある質問","id":"Sering ditanyakan"},
}

LOCALES = ["es","fr","de","pt","it","nl","tr","uk","ru","ar","hi","bn","zh","ja","id"]

# English fallback for keys that have no translation in a given locale.
EN_FALLBACK = {k: v for k, v in [
    ("tab.overview","Overview"),("tab.pl","P&L"),("tab.cash_flow","Cash Flow"),
    ("tab.sources_uses","Sources & Uses"),("tab.unit_econ","Unit Economics"),
    ("tab.scenarios","Scenarios"),("tab.cap_table","Cap Table"),
    ("tab.valuation","Valuation"),("tab.sensitivity","Sensitivity"),
    ("tab.calculations","Calculations"),
] + [(k, "TODO") for k in TRANSLATIONS.keys()]}

def append_to_locale(code):
    """Append the new keys to dictionaries/<code>.ts just before the closing brace."""
    path = ROOT / f"{code}.ts"
    content = path.read_text(encoding="utf-8")

    # Skip if already present
    if '"tab.overview"' in content:
        print(f"  {code}: already has tab.overview, skipping")
        return

    lines = []
    lines.append('')
    lines.append('  // ── Output pages + pricing (batch 3) ────────────────────────────────────')
    for key in TRANSLATIONS:
        per_lang = TRANSLATIONS[key]
        if code in per_lang:
            value = per_lang[code]
        else:
            value = EN_FALLBACK.get(key, "TODO")
        # Escape backslashes and double-quotes for the JSON-like literal
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'  "{key}": "{escaped}",')

    block = "\n".join(lines) + "\n"

    # Insert before the final closing '};'
    closing = "\n};\n"
    if not content.rstrip().endswith("};"):
        print(f"  {code}: unexpected ending, skipping")
        return
    new = content.rstrip().rstrip("};").rstrip() + "\n" + block + "};\n"
    path.write_text(new, encoding="utf-8")
    print(f"  {code}: appended {len(TRANSLATIONS)} keys")

for code in LOCALES:
    append_to_locale(code)
print("done.")
